### ISSUE TITLE
Is there a way to programmatically open the modal? 

### ISSUE THREAD

**Issue by sanbornsen** [plaid/react-plaid-link#102]
Right now the modal opens on the click in the child component. Is there any way to open it programmatically? Some prop for that?

**Comment by kiranparab0** [comment]
I am also finding a same workaround. Below is what I am trying. After redirecting back from banks page, the I am expecting the modal should open automatically. But nothing happens.

    import React, { useCallback, useEffect } from 'react';
    import { PlaidLink, usePlaidLink } from 'react-plaid-link';
    import Settings from "../../../utils/settings.utils";

    const PlaidConsent = props => {
        const onSuccess = useCallback(
            (token, metadata) => console.log('onSuccess', token, metadata),
        []);

        const onEvent = useCallback(
            (eventName, metadata) => console.log('onEvent', eventName, metadata),
        []);

        const onExit = useCallback(
            (err, metadata) => console.log('onExit', err, metadata),
        []);

        const plaidConfig = {
            clientName: Settings.clientName || 'EY Banks Connector',
            env: Settings.plaid.env || 'sandbox',
            product: Settings.plaid.product || ['auth', 'transactions'],
            publicKey: Settings.plaid.publicKey || '...',
            token: Settings.plaid.token,
            onSuccess,
            onEvent,
            onExit,
            oauthRedirectUri:window.location.origin+"/oauth-consent?req="+props.requestId,
            oauthNonce:"some-long-nonce-value",
            oauthStateId:props.oauthStateId
        };

        const { open, ready, error } = usePlaidLink(plaidConfig);

        useEffect(() => {
            if(ready){
                open();
            }
        },
        [ready])

        return (
            <>
                <button
                    id="btnPlaidLink"
                    type="button"
                    className="button"
                    onClick={() => open()}
                    disabled={!ready || error}
                >
                    Open Plaid Link
                </button>
            </>
        );  
    };
    export default PlaidConsent;`

**Comment by alan345** [comment]
same here.. nothing happens.
I got no errors!

```
  React.useEffect(() => {
    if (ready) {
      try {
        open()
      } catch (e) {
        console.log(e)
      }
    }
  }, [ready])
```

**Comment by kiranparab0** [comment]
I found onLoad event in plaid component. This is a callback that is called when the Link module has finished loading. 

    loadHandler = () => {
        this.setState({isPlaidReady: true});
        const elm = document.getElementsByClassName("btnOpenPlaid")[0];
        elm.click();
    }

    <PlaidLink
        className="btnOpenPlaid"
        style={{ marginTop: '10px'},this.state.isPlaidReady? {} : {display: 'none'}}
        clientName={Settings.clientName}
        env={Settings.plaid.env || 'sandbox'}
        product={Settings.plaid.product || ['transactions', 'auth']}
        publicKey={Settings.plaid.publicKey}
        token={Settings.plaid.token}
        countryCodes={['US','CA','GB','FR','ES']}
        onExit={this.exitHandler}
        onSuccess={this.successHandler}
        onEvent={this.eventHandler}
        oauthRedirectUri={window.location.origin+"/oauth-consent?req="+this.props.requestId}
        oauthNonce="some-long-nonce-value"
        oauthStateId={this.props.oauthStateId}
        onLoad={this.loadHandler}
    >

**Comment by alan345** [comment]
thanks @kiranparab0 
With hooks, for some reason, it works with 2 actions: `elm.click()` and `open()`. I still cannot figure out why..
But it works

```
  const onLoad = () => {
    const elm: any = document.getElementsByClassName('btnOpenPlaid')[0]
    elm.click()
    open()
  }
```

and
```
          <Button onClick={() => open()} disabled={!ready} className="btnOpenPlaid">
            Add Bank Account
          </Button>
```

**Comment by alan345** [comment]
even more weird. This work too..

```
  const onLoad = () => {
    const elm: any = document.getElementsByClassName('btnOpenPlaid')[0]
    elm.click()
    elm.click()
  }
```
