### ISSUE TITLE
Update mode onSuccess callback response objects

### ISSUE THREAD

**Issue by cthomaschase** [plaid/react-plaid-link#106]
Not sure this is the right forum. If not please redirect me, thanks.

After updating an item previously in an error state, via the Update mode workflow, the response objects change (particularly the accounts array) depending on the Select Account option I choose in the link configurator.

When Select Account is disabled, the onSuccess callback contains a populated accounts object. When enabled, the response contains an empty accounts object.

Is this intended behavior, did I miss something in the documentation?

**Comment by skylarmb** [comment]
just doing a sweep of old issues here...

@cthomaschase If this is still an issue for you please reach out to the support team through dashboard.plaid.com.
