### ISSUE TITLE
Is there a way to open PlaidLink on a specific institution?

### ISSUE THREAD

**Issue by fforres** [plaid/react-plaid-link#108]
We are looking into options for this. 
Was wondering if there is a way to pre-select the institution (or pass a parameter to pre-filter/search the institutions list)?

(Was this a feature ever or removed at some point?)

Thanks for the integration btw :)

**Comment by abartolo** [comment]
@fforres Just found out that you can pass in an `institution type` to the `open()` but that is not this library currently doesn't support.

I plan to create an MR today to implement the fix I did locally to get it to work.

Note - Even with this fix it might not worked. I found out there needs to be some settings in the /dashboard config to allow opening directly to a specific institution.

**Comment by abartolo** [comment]
MR open to resolve support for anyone that allows additional arguments to `open` https://github.com/plaid/react-plaid-link/issues/108

**Comment by cgfarmer4** [comment]
Hi @fforres-
This method has been deprecated and we suggest you use the full link flow. If you have more questions please reach out to your account manager and they can provide more details.
