### ISSUE TITLE
Plaids instance not destroyed.

### ISSUE THREAD

**Issue by somnathghadge** [plaid/react-plaid-link#110]
We are using this package for plaid implementation. But we are facing issues like whenever we tried to launch the plaid it creates the new instance of it and does not destroy it any of the instances. As we as its taking the onSuccess of the first instance only. I think if we destroy the instance after closing the plaid then this issue will be resolved. Attaching plaid instances image for your reference.
![image](https://user-images.githubusercontent.com/7940539/82600707-f936b580-9bcb-11ea-838e-5c2ee792886c.png)

**Comment by alexandrasmith00** [comment]
I'm also encountering this issue, but it seems to destroy properly on `onSuccess` callback, but not on `onExit` callback

**Comment by somnathghadge** [comment]
We are facing this issue for `onSuccess` callback.

**Comment by anjiren** [comment]
Hi @somnathghadge and @alexandrasmith00 - we're taking a look at this within our shared web-client library. Will circle back with updates.

**Comment by abartolo** [comment]
@anjiren  Any update on this? Can this expain why we are seeing `Link warning: attempted to exit Link when it was not open`?

**Comment by alexandrasmith00** [comment]
@anjiren Any update on this? Right now, the `onSuccess` callback is being invoked multiple times as a result

**Comment by skylarmb** [comment]
@alexandrasmith00 @abartolo @somnathghadge are you still seeing this issue on the latest version of react-plaid-link? I want to determine if https://github.com/plaid/react-plaid-link/pull/109 fixed this issue

**Comment by cgfarmer4** [comment]
Closing due to lack of response. Please reopen if this is still an issue.
