### ISSUE TITLE
Handlers (onSuccess, onEvent) fire twice if you navigate pages

### ISSUE THREAD

**Issue by oaosman84** [plaid/react-plaid-link#113]
This might be related to #110 , but is slightly more dangerous.
1) Initialize the Plaid hook.
2) `open` the Plaid flow, then immediately exit without going through the flow.
3) Navigate (SPA) to a different page, then navigate back, you'll get a message like:
```
react_devtools_backend.js:6 Link warning: attempted to exit Link when it was not open 
```
4) Re-`open` Plaid flow. All events are fired twice.

The dangerous piece here is that the onSuccess event (in addition to onEvent) will fire twice once a user goes through the flow, which means if you're doing any work like an API call to exchange token, that API call will fire twice.

**Comment by oaosman84** [comment]
This is fixable by https://github.com/plaid/react-plaid-link/pull/109, so closing this.

**Comment by anamake** [comment]
I can confirm I'm seeing this issue as well when navigation to different routes/pages on a SPA. @oaosman84 @goleary
