### ISSUE TITLE
Plaid v2.3.0-alpha.0 using and old version of react-script-hooks

### ISSUE THREAD

**Issue by Ruk33** [plaid/react-plaid-link#117]
Hello, for the version `v2.3.0-alpha.0` you guys are using an old version of `react-script-hook` (https://github.com/plaid/react-plaid-link/blob/v2.3.0-alpha.0/package.json#L46) that does not support the property `checkForExisting` introduced in version 1.1.0 (this is fine on the master branch as noticed here https://github.com/plaid/react-plaid-link/blob/master/package.json#L46).

Just wanted to point this out since, without this property, the plaid script gets loaded for every render causing undesired effects.

Regards.

**Comment by cgfarmer4** [comment]
hi @Ruk33- thanks for the report. This is on master but Im wondering if these might be related? https://github.com/plaid/react-plaid-link/issues/110

**Comment by Ruk33** [comment]
Hello @cgfarmer4. Will check and let you know.

**Solution**: in the meantime, we solved this issue by manually including the script in the HTML.

**Comment by skylarmb** [comment]
hello @Ruk33 please upgrade to the latest version. this was fixed in https://github.com/plaid/react-plaid-link/pull/109
