### ISSUE TITLE
Styling PlaidLink in 2.0

### ISSUE THREAD

**Issue by dwixom** [plaid/react-plaid-link#120]
Hello, I've updated to the most recent version of react-plaid-link but it currently looks like the HOC is coming with some strange inline stylings which are difficult to override. Before, passing an empty style attribute worked, but even that seemed unnecessary. 

These are the inline styles being applied, which makes it very annoying to use on any app with a white background.

![Screen Shot 2020-06-30 at 3 57 23 PM](https://user-images.githubusercontent.com/8524054/86185249-c0eb9680-baea-11ea-9744-9ce73f627441.png)

Below see my terrible solution, which includes overriding the inline style properties with invalid entries to allow the styling from my button class to take hold.

![Screen Shot 2020-06-30 at 3 54 29 PM](https://user-images.githubusercontent.com/8524054/86185272-d1037600-baea-11ea-8f1a-70137bf924d7.png)

<img width="309" alt="Screen Shot 2020-06-30 at 3 54 13 PM" src="https://user-images.githubusercontent.com/8524054/86185313-e678a000-baea-11ea-8bf4-9b678104c520.png">

Is there a better way to do this?

**Comment by cgfarmer4** [comment]
hi @dwixom- We provide react hooks for styling your own button.

**Comment by jordanbtucker** [comment]
I think @cgfarmer4 is saying to just copy the HOC into your own file and tweak it to make your own HOC styled the way you want. Personally, I don't see why you would even want a pre-styled button when you provide `className` and `style` props already. This button is going to look out of place in most UIs, so just let the user style it.
