### ISSUE TITLE
Mention publicKey alias for key in documentation or switch the logic

### ISSUE THREAD

**Issue by ewalti** [plaid/react-plaid-link#126]
The documentation states:

```
  const config = {
    token: '<GENERATED_LINK_TOKEN>',
    onSuccess,
    // ...
  };
```

and references [Official Plaid Link docs](https://plaid.com/docs/#creating-items-with-plaid-link) as a source of truth. According to the official documentation, one must provide `Plaid.create()` with a `key`. If you provide this library a `key` in `config`,   ` link-initialize.js` complains `Uncaught Error: Missing Link parameter. Link requires a key or token to be provided.`. However, if you use `publicKey` which [factory.ts](https://github.com/plaid/react-plaid-link/blob/master/src/factory.ts#L42) converts, it works fine.

There is no mention of `publicKey` in the documentation. It should be added. I would recommend using `key` for consistency with the official documentation, but realize that `key` may not be a good fit as it has a special place in `React`.

I'm happy to issue a PR depending on the choice.

Tested in a [standalone app](https://codesandbox.io/s/gifted-gates-ujvix?file=/src/App.js) using:

```
import React from "react";
import { usePlaidLink } from "react-plaid-link";

const noop = () => {};

function App() {
  const config = {
    clientName: "Plaid Quickstart",
    // key: process.env.REACT_APP_PLAID_PUBLIC_KEY,
    publicKey: process.env.REACT_APP_PLAID_PUBLIC_KEY,
    onLoad: noop,
    onSuccess: noop,
    onExit: noop,
    onEvent: noop
  };
  const { open } = usePlaidLink(config);
  return (
    <div className="App">
      <header className="App-header">
        <button onClick={() => open()}>Add a bank account</button>
      </header>
    </div>
  );
}

export default App;
```

**Comment by otherchen** [comment]
Hey @ewalti! Apologies for the confusion here. The public_key is actually being deprecated as the way to initialize Link and we now recommend that all new Link integrations use the new `link_token`. You can read more about how to create one here - https://plaid.com/docs/#create-link-token

**Comment by skylarmb** [comment]
@otherchen can this be closed or is there any action item here?
