### ISSUE TITLE
The back arrow stops working, when you click through to "Learn more about Plaid".

### ISSUE THREAD

**Issue by HatemRamadan** [plaid/react-plaid-link#129]
After initializing Plaid Link and going through it to "Learn more about Plaid" page, I cannot go back using the back arrow on the top left.

Watch behavior here => 
https://www.loom.com/share/362421c9ebbc429cb0fe1013821bb3b4

**Comment by cgfarmer4** [comment]
hi @HatemRamadan- Thanks for your report. I have confirmed your issue and filed a bug. Will update this when the fix has been made.

**Comment by cgfarmer4** [comment]
Fix has been implemented @HatemRamadan.
