### ISSUE TITLE
what are the breaking changes in 3.0?

### ISSUE THREAD

**Issue by RwwL** [plaid/react-plaid-link#130]
Looking for release notes but failing to find them so far; apologies if I'm missing something obvious.

Edit: took note of "Add Link token options to initialization and move onEvent types to their own interface." in the changelog but not 100% clear on what, if anything, will need to change in consuming code.

**Comment by cgfarmer4** [comment]
hi @RwwL, usage of the `public_key` is in the process of being deprecated in v3. You library should continue to function as normal if previously using it.
