### ISSUE TITLE
Specify institution?

### ISSUE THREAD

**Issue by nateabele** [plaid/react-plaid-link#131]
Using Plaid Link to re-authenticate an institution appears to operate at the user level, without the ability to specify which institution you want to re-link, such that if multiple institutions need re-authentication, users can't pick which one they want to re-link. Is there a plan to make this possible?

Thanks.

**Comment by cgfarmer4** [comment]
hi @nateabele- The ability to launch Link to a specific institution is not supported.

**Comment by nateabele** [comment]
Yeah, clearly not. Is there any plan to support it?

**Comment by cgfarmer4** [comment]
No, we encourage our users to use the whole Link flow. If you have further concerns, please contact your account manager.
