### ISSUE TITLE
Use Country Codes options

### ISSUE THREAD

**Issue by juanmarinballastlane** [plaid/react-plaid-link#132]
Hello guys

This library supports `country_codes` attribute, I tried to use `countryCodes={['US', 'CA']}` but apparently is not working.

Thanks

**Comment by cgfarmer4** [comment]
hi @juanmarinballastlane- can you provide more details about your setup? This should work so Im curious what you are seeing.

**Comment by skylarmb** [comment]
I think the issue is @juanmarinballastlane is using the `@types/react-plaid-link` package, which is out of date (needs to be deprecated) and not required anymore since `react-plaid-link` [exposes its own types now](https://github.com/plaid/react-plaid-link/blob/master/src/types/index.ts#L31).
