### ISSUE TITLE
Fail to remove the Plaid iframe when unmounting

### ISSUE THREAD

**Issue by josenunes-advizr** [plaid/react-plaid-link#133]
This is probably a regression of https://github.com/plaid/react-plaid-link/issues/30

The Plaid iframe is not being removed from the DOM after unmounting the `usePlaidLink` hook.

Step to reproduce:
- react-plaid-link v3.0.0
- Run Storybook locally
- Go to "react-plaid-link > hooks" story
- Insert a valid link token in the Knobs tab
- Click the button to open Plaid Link (⚠️ Important)
- Close Plaid Link
- Unmount the `usePlaidLink` hook by going into a different story
- See the iframe still in the DOM (it does not get removed)

**Comment by armsteadj1** [comment]
You should be able to call `exit()` when the component is unmounting. 

It's not in the README, although it looks like `exit` is returned:

https://github.com/plaid/react-plaid-link/blob/6b6cc965fb470ecf23415b0da0860d3d150681e3/src/usePlaidLink.ts#L66

**Comment by josenunes-advizr** [comment]
Closing, the issue seems to have been fixed in https://github.com/plaid/react-plaid-link/pull/146 (now part of v3.1.1)
