### ISSUE TITLE
Plaid exit after onSuccess

### ISSUE THREAD

**Issue by PraveenPuvvula** [plaid/react-plaid-link#138]
I'm trying to forcefully exit plaid as soon as onSucess is fired. I have used a standard react implementation without hooks, and I don't intend on using hooks in this application anytime soon.

`<PlaidLink
                  linkCustomizationName="..."
                  publicKey={plaidAuthentication.key}
                  apiVersion={plaidAuthentication.apiVersion}
                  onSuccess={onSuccess}
                  className={styles.plaid}
                  onEvent={onEvent}
                  onExit={onExit}
                  // how do I get this to work? exit={this.exit()}
                >`

The reason I want to forcefully exit plaid is because I don't want the users to see the login successful screen of plaid as attached. Can anyone help me with how to use the exit or destroy functions? Thank you.
![loginSuccess](https://user-images.githubusercontent.com/20115527/93363430-3aa33e80-f815-11ea-8c3c-a667bf673393.jpg)

**Comment by skylarmb** [comment]
hi @PraveenPuvvula sorry if I am misunderstanding something here, but can't you just un-render the `PlaidLink` component? When that component unmounts it destroys Link. I tested this out like so and it appears to work fine.

```tsx
import React from 'react';

import { PlaidLink } from 'react-plaid-link';

const App = (props) => {
  const onExit = (error, metadata) => console.log('onExit', error, metadata);
  const onEvent = (eventName, metadata) =>
    console.log('onEvent', eventName, metadata);
  const onSuccess = (token, metadata) =>
    console.log('onSuccess', token, metadata);

  const [showLink, setShowLink] = React.useState(true);

  return (
    <>
      <button onClick={() => setShowLink(!showLink)}>toggle link</button>
      {showLink && (
        <PlaidLink
          token={props.token}
          onExit={onExit}
          onSuccess={onSuccess}
          onEvent={onEvent}
        >
          Open Link and connect your bank!
        </PlaidLink>
      )}
    </>
  );
};

export default App;

```
