### ISSUE TITLE
onEvent only firing when Link is closed

### ISSUE THREAD

**Issue by raylenmargono** [plaid/react-plaid-link#139]
Hi everyone,

Wanted to leverage the onEvent hook to see when institutions are selected. I noticed that all events except for OPEN are fired only when Link is closed. This behavior is also apparent in the implementation in the storybook as well.

Let me know how I can be of help to diagnose this further and if there is another work around. Attached is the console logs from storybook.

![Screen Shot 2020-09-22 at 1 58 54 PM](https://user-images.githubusercontent.com/5940684/93919525-d2a09c80-fcdb-11ea-9e41-b5d7e25eb042.png)
(Notice no console logs for events)

![Screen Shot 2020-09-22 at 1 59 02 PM](https://user-images.githubusercontent.com/5940684/93919555-da604100-fcdb-11ea-809f-9f38fe746eb3.png)
(Once closed all events fire)

**Comment by skylarmb** [comment]
hello @raylenmargono this is by design, this is not a bug. https://plaid.com/docs/#onevent-callback

If you need to know when an event happened, each event has a `timestamp` on it.

These events can be used for your analytics or to inform your application logic after the Link flow is complete.

**Comment by raylenmargono** [comment]
@skylarmb is there a way for us to detect when a user has selected an institution?

**Comment by skylarmb** [comment]
@raylenmargono no.

**Comment by stevegraham** [comment]
@aylenmargono this was the original behavior but Plaid made a breaking change to their API contract to stop this - https://blog.teller.io/2020/06/17/migrate-to-teller.html. Plaid changed this pretty much as soon as that blog post was published, and what's interesting they still allow certain customers to use the old behavior if they have enough leverage over Plaid, i.e. they are large customers. Check your Plaid Link feature flags, the flag pertaining to this behavior is called `external_event_queue`.

**Comment by tkaycodes** [comment]
Is there a way for us to know if there is an error ? 

 this.onEvent = function (eventName, metadata) {
    if (eventName === 'ERROR') {
           // looking to capture this
    }
}

This is also firing AFTER link is closed. Is there any way to capture this when it happens ?

**Comment by jlally21** [comment]
@tkaycodes  @raylenmargono   Did you end up finding a workaround for this?  I am also looking to capture all ERROR events when they occur, not just AFTER Link is closed, as it's not guaranteed the user will close Link (e.g. they may close the browser window)
