### ISSUE TITLE
Using 'auth' and 'identity' products on same instance

### ISSUE THREAD

**Issue by camilobern** [plaid/react-plaid-link#140]
We depend on the `auth` and `identity` products to both create institution links and verify corresponding bank identities against our platform. 

So far we have been able to do this by initializing `PlaidLink` with the products mentioned above (i.e. `product={['auth', 'identity']}`)

Now we have decided to enable `Same Day Microdeposits` to allow users to add institutions not included in the regular auth flows. However, it seems like the only way to achieve this is to initialize with `auth` as the only product.

Is there any way to have the same `PlaidLink` instance supporting both `auth`, `identity` products and `Same Day Microdeposits` ? It would seem the workaround is to have two instances, which seems awkward. Unless we could have a separate option that could launch straight to the `Same Day Microdeposits` flow.

**Comment by skylarmb** [comment]
hey @camilobern sorry for the late response here, just cleaning out old issues. You can always call any product endpoints later after the item is created. As seen in our [docs](https://plaid.com/docs/auth/coverage/automated/#configure--create-a-link_token) for implementing microdeposits, the recommendation here is to just initialize with `auth` and call `identity` later once you have created the access_token and once you have received a successful [webhook](https://plaid.com/docs/auth/coverage/automated/#handle-auth-webhooks) that indicates microdeposits were successful. Your app will just need to account for the case where identity is unavailable.

**Comment by skylarmb** [comment]
I dont know what the answer is off the top of my head but I suspect there are relatively few institutions that support auth and not identity, but you should still account for that case. You could figure this out with the `/institutions/get` api
