### ISSUE TITLE
`selectAccount` is not defined in `PlaidLinkOptions`

### ISSUE THREAD

**Issue by nitruxa** [plaid/react-plaid-link#143]
`selectAccount` is not defined in `PlaidLinkOptions` so typescript fails when added to `usePlaidLink`, but account selection process itself works:
```
(property) selectAccount: boolean
Argument of type '{ token: string; env: string; selectAccount: boolean; onSuccess: (token: any, metadata: any) => void; }' is not assignable to parameter of type 'PlaidLinkOptions'.
```

**Comment by skylarmb** [comment]
hi there @nitruxa. Are you using Link tokens? Here is the [migration guide](https://plaid.com/docs/link/link-token-migration-guide/) if you have not updated to use Link tokens yet. Our up to date releases of our SDKs such as this  one, `react-plaid-link`, only support our current API version.

The way to do this is by enabling account selection in your Link configuration in the dashboard ([docs](https://plaid.com/docs/link/customization/#select-account), [dashboard link](https://dashboard.plaid.com/link/account-select)) and specify the link config you would like for a particular token  in the `link_customization_name` field in your [`/link/token/create` call].
