### ISSUE TITLE
Plaid loads different UI on electron browser as against the chrome  browser

### ISSUE THREAD

**Issue by prashantabellad** [plaid/react-plaid-link#144]
Issue: Plaid loads different UI on electron browser as against the chrome  browser

**On Chrome browser**:
![image](https://user-images.githubusercontent.com/10412309/95757854-4d4e4d80-0cc5-11eb-8a48-9f2600962fa5.png)

**On Electron browser**: Previously on electron browser Plaid used to load the same UI as it is on Chrome browser. Now it has changed to below
Electron version: based on Chromium 80
![image](https://user-images.githubusercontent.com/10412309/95757178-70c4c880-0cc4-11eb-80b3-4fe53315fc58.png)

**Expected**
Plaid should load the same UI as on Chrome browser.
For us it at least impacts our automated test suites that run on electron browser

**Comment by skylarmb** [comment]
@prashantabellad I believe you simply entered into an A/B design test in our flow. If you clear cookies/cache in Electron and try opening Link again you may see a different result. We regularly run experiments to improve conversion rate in Link, which helps your users connect their bank accounts more often.

**Comment by prashantabellad** [comment]
@skylarmb the electron browser is getting used in our automation test tool (cypress.io) and it executes in fresh browser every time, so this is not a cache issue. Can you pls help here?

**Comment by skylarmb** [comment]
@prashantabellad are you still seeing this behavior now? Or did you only see ~1wk ago?

**Comment by prashantabellad** [comment]
> @prashantabellad are you still seeing this behavior now? Or did you only see it ~1wk ago when you filed the issue?

I am still seeing this issue

**Comment by skylarmb** [comment]
@prashantabellad thanks, ive filed a ticket for our eng team to take a look at this, thanks for flagging.

**Comment by skylarmb** [comment]
@prashantabellad you will notice that this new design is now rolled out to everyone on all platforms in Link. See our blog post here: https://blog.plaid.com/the-all-new-plaid-link/
