### ISSUE TITLE
IE11 Error "Object doesn't support property or method 'remove'"

### ISSUE THREAD

**Issue by rosscredible** [plaid/react-plaid-link#145]
The `link-initialize.js` script is throwing a runtime error `Object doesn't support property or method 'remove'` when trying to use the `react-plaid-link` hook in IE11.  Does this library support IE11?

**Comment by skylarmb** [comment]
hi @rosscredible `link-initialize.js` is actually not a script from this package, `react-plaid-link`, its part of the Plaid iframe that gets injected into the page by this SDK. I have filed a ticket to check on this upstream in Link. We do support IE 11, so if this reproduces, it would be a bug. Thanks for the report!
