### ISSUE TITLE
@skylarmb the electron browser is getting used in our automation test tool (cypress.io) and it executes in fresh browser every time, so this is not a cache issue. Can you pls help here?

### ISSUE THREAD

**Issue by prashantabellad** [plaid/react-plaid-link#147]
@skylarmb the electron browser is getting used in our automation test tool (cypress.io) and it executes in fresh browser every time, so this is not a cache issue. Can you pls help here?

_Originally posted by @prashantabellad in https://github.com/plaid/react-plaid-link/issue_comments/709759420_

**Comment by skylarmb** [comment]
original issue: #144
