### ISSUE TITLE
500 error trying finishing connecting to Plaid Platypus Oauth

### ISSUE THREAD

**Issue by dustinhorton** [plaid/react-plaid-link#151]
Using `3.0.0`.

I'm supplying the same `token` & a `receivedRedirectUri`, but it looks like link goes from a `SELECT INSTITUTION` to a 500 on `sandbox.plaid.com/link/item/mfa`

![Screen Shot 2020-10-20 at 3 20 18 PM](https://user-images.githubusercontent.com/378165/96753084-57470f00-139d-11eb-9d23-8fafb1b38315.png)

**Comment by otherchen** [comment]
Hey @dustinhorton, thanks for creating this issue! Do you mind elaborating on your flow a bit more?

It seems like what you're saying is that after the oauth flow is complete and you are redirected back to Link, Link fails on `/link/item/mfa`, right? If this is the case, do you mind pasting the `link_token` that you used for this Link session?

**Comment by dustinhorton** [comment]
@otherchen Thanks—haven't quite been able to circle back to this yet, but intend to.

You are correct in what I was experiencing. To unblock myself, I reverted back to loading `https://cdn.plaid.com/link/v2/stable/link-initialize.js` and calling `window.Plaid.open()` from that, and it worked as expected.

**Comment by otherchen** [comment]
Thanks! I'm closing for now since this seems resolved.
