### ISSUE TITLE
unable to enter text into input when I useLink with link_token

### ISSUE THREAD

**Issue by goleary** [plaid/react-plaid-link#152]
I just started getting many errors going into `ITEM_LOGIN_REQUIRED` out of the blue.  I just implemented the flow to get a `link_token` from the server to enable users to relink their items, but when this link is created and they get to the username/password fields they are unable to enter any text.

As soon as you click into the input field focus is lost and no text can be entered.

The link component works perfectly when no `link_token` is provided.

**Comment by otherchen** [comment]
Hey @goleary, thanks for creating this issue! Do you mind pasting the `link_token` that you're running into this issue with so that we can further investigate?

**Comment by goleary** [comment]
Hey @otherchen! Here's the token: `link-production-63a8305e-5267-4c77-8c58-77d6d5782ca2`

Here's a video where you can see what I'm talking about:

https://www.loom.com/share/2878fa33ac7b464d97f58c223dec4191

**Comment by goleary** [comment]
any suggestions? 
I'm having more customers accounts go into a state where they need to relink and it's not possible due to this bug...seriously degrading the experience of my application.

**Comment by otherchen** [comment]
Hey @goleary, really sorry for the delayed response! 

I just tried to recreate this issue using the storybook sample app in this repo and I was not able to recreate it 🙁 . I'm using Chrome, Node 10, and followed the following steps:

1. Curl `/link/token/create` in the sandbox environment
2. Go through the normal Link flow once to get a `public_token`
3. Curl `/item/public_token/exchange with that `public_token` to get an `access_token`
4. Curl `/item/sandbox/item/reset_login` with that `access_token` to put it in an `ITEM_LOGIN_REQUIRED` state.
5. Curl `/link/token/create` with the `access_token` to configure the `link_token` for update_mode.

At this point I have a sandbox `link_token` configured for update mode.

I then started the storybook app by:
1. `git clone https://github.com/plaid/react-plaid-link.git`
2. verify that you're using Node.js version 10+
3. `make setup`
4. `make storybook`
5. open `localhost:6006`

At this point the storybook app in the `react-plaid-link` repo should be started. I then:

1. paste in your `link_token` inside the `token` input on the right hand-side
2. click `Save Link Configuration`
3. click the `Open Plaid Link`
4. verify if I could enter text into the text boxes

Here's it working successfully for me:
![Kapture 2020-11-19 at 16 56 24](https://user-images.githubusercontent.com/8565076/99742475-626a8900-2a88-11eb-91ca-947e718ceacf.gif)

If you follow the above steps and it's still not working for you, do you mind going into the Plaid Dashboard and filing a support ticket?

**Comment by goleary** [comment]
hey @otherchen, no worries and now I've got to apologize for not updating this issue once I got more information earlier this week:

I noticed this only happens when my link is created from within a [material-ui Dialog component](https://material-ui.com/components/dialogs/). I'm using v4.10.0 in case you go looking, not sure if it's an issue with the latest version.

I plan to update material-ui and if it's still happening then move the link spawning to another component other than the Dialog.

Thanks for looking into this. I'll make sure to report back here once I have a chance to work on this some more.

**Comment by mckenziekennelly13** [comment]
I am having the same issue @goleary. PlaidLink is not allowing me to type and is glitching in a material-ui dialog component. I have v4.11.

**Comment by mckenziekennelly13** [comment]
Hi @goleary. I had the same issue with the material ui dialog component and plaidlink glitching. I added disableEnforceFocus as a prop to the dialog and it's working fine now.

**Comment by goleary** [comment]
Wow, thanks, great tip @mckenziekennelly13! I already refactored my App to avoid loading the `PlaidLink` from a modal/dialog, but this would have been much simpler.

I'll go ahead and close this because it clearly has nothing to do with react-plaid-link

**Comment by walter-grace** [comment]
> Hey @goleary, really sorry for the delayed response!
> 
> I just tried to recreate this issue using the storybook sample app in this repo and I was not able to recreate it 🙁 . I'm using Chrome, Node 10, and followed the following steps:
> 
> 1. Curl `/link/token/create` in the sandbox environment
> 2. Go through the normal Link flow once to get a `public_token`
> 3. Curl `/item/public_token/exchange with that `public_token`to get an`access_token`
> 4. Curl `/item/sandbox/item/reset_login` with that `access_token` to put it in an `ITEM_LOGIN_REQUIRED` state.
> 5. Curl `/link/token/create` with the `access_token` to configure the `link_token` for update_mode.
> 
> At this point I have a sandbox `link_token` configured for update mode.
> 
> I then started the storybook app by:
> 
> 1. `git clone https://github.com/plaid/react-plaid-link.git`
> 2. verify that you're using Node.js version 10+
> 3. `make setup`
> 4. `make storybook`
> 5. open `localhost:6006`
> 
> At this point the storybook app in the `react-plaid-link` repo should be started. I then:
> 
> 1. paste in my `link_token` inside the `token` input on the right hand-side
> 2. click `Save Link Configuration`
> 3. click the `Open Plaid Link`
> 4. verify if I could enter text into the text boxes
> 
> Here's it working successfully for me:
> ![Kapture 2020-11-19 at 16 56 24](https://user-images.githubusercontent.com/8565076/99742475-626a8900-2a88-11eb-91ca-947e718ceacf.gif)
> 

Is this how you create a 'link token' I seem to be able to create an access-sandbox. I am having trouble getting my react app to do anything using the example on the home page which is just a button. Any clarity around how to create a link token?
