### ISSUE TITLE
Feature Request - Bank Blocklist

### ISSUE THREAD

**Issue by liplylie** [plaid/react-plaid-link#155]
Hi,

For one of my projects, we need functionality where we do not accept certain banks. Is it possible to add a blacklist prop to prevent certain banks from showing?

For now, I just added logic to `onSuccess` to prevent storing data from banks that we are not accepting.

**Comment by skylarmb** [comment]
hi @liplylie there is no hidden feature/parameter that you are missing or something. thanks for the feedback! I have added a feature suggestion to our internal product feedback, so i am going to close this for now.

**Comment by skylarmb** [comment]
actually looks like we leave feature request issues as Open status. re-opening

**Comment by skylarmb** [comment]
Closing this as I have confirmed this is not something Plaid supports and not something we plan to implement.
