### ISSUE TITLE
Is there a way to pass institution id to link?

### ISSUE THREAD

**Issue by alansouzati** [plaid/react-plaid-link#158]
I want to skip the search step and go straight to the bank credentials page, something along these lines:

```
const { open, ready } = usePlaidLink({
    onSuccess,
    token,
    institutionId: 'ins_3',
  });
```

context, I have a manual institution created using the search endpoint, so I do have the institution id. Now, users want to convert this institution to an automated plaid flow. It would be nice for the user to not have to search for the institution before they are allowed to enter the credentials.

**Comment by daniellacoste** [comment]
Hey @alansouzati ,

Daniel from Plaid Support here — thanks for your patience! For context, Plaid Link used to allow for this functionality but we no longer allow for this type of integration. I'm sorry for any inconvenience this may cause you, but we appreciate your feedback. Please reply here or [contact Plaid Support from your Plaid Dashboard](https://dashboard.plaid.com/support) if you have any more questions.

**Comment by skylarmb** [comment]
this was re-opened accidentally
