### ISSUE TITLE
Plaid keeps on flickering and couldn't enter account details

### ISSUE THREAD

**Issue by hari-criticalasset** [plaid/react-plaid-link#160]
Plaid keeps flickering and doesn't allow to enter account details.

When clicked on the input, it is getting focused but defocused instantly due to flickering.

Here is a video of the issue reproduction:

https://drive.google.com/file/d/1wr2kVA7fNegWvbTjIN_5XzNLBSSVKLud/view?usp=sharing

**Comment by aeidelson** [comment]
Hello @hari-criticalasset,

I'm sorry to see that you've been having problems.

We haven't been able to reproduce this issue on our side and wonder if it may be related to the specifics of your page. Would it be possible to share a page (or a url) where this bug occurs? It would also be helpful to know what browser and version you are using.

Thank you!

**Comment by daniellacoste** [comment]
Hey @hari-criticalasset,

Daniel from Plaid Support — I'll give you an assist with this issue in the Support ticket you filed. Thanks for flagging!

**Comment by hari-criticalasset** [comment]
Thanks @daniellacoste , @aeidelson 

Chakra UI implements data-focus-guard="true" to enforce focus into Drawers and Modals.

This was fixed by using "trapFocus" property.

**Comment by osdiab** [comment]
For anyone that runs into this issue: my company also saw this behavior, but we don't use `react-plaid-link` (we just use the normal script tag) nor do we use Chakra UI. The reason it happened was because we triggered the plaid modal to open more than once on a single page. As a result, the multiple Plaid instances competed with each other for focus, causing it to be unusable. Hope this helps someone!

**Comment by reggieofarrell** [comment]
For anyone using Material UI... if your are loading Plaid inside of a dialog/drawer, you have to put `disableEnforceFocus` on the modal/drawer

**Comment by mlakmal** [comment]
> For anyone using Material UI... if your are loading Plaid inside of a dialog/drawer, you have to put `disableEnforceFocus` on the modal/drawer

@reggieofarrell  thanks this issue came up on our app as well with material-ui dialogs

**Comment by makeitraina** [comment]
> For anyone using Material UI... if your are loading Plaid inside of a dialog/drawer, you have to put `disableEnforceFocus` on the modal/drawer

Thank you @reggieofarrell.

This comment is about to save thousands of peoples, a lot of time! Plaid should seriously have something related to this in their docs.

**Comment by TannerPlauche** [comment]
Thank you @reggieofarrell. This was giving me lots of trouble. That fixed it. THANK YOU!!!

**Comment by yousefa00** [comment]
@hari-criticalasset how exactly did you fix this? Where do you pass `trapFocus`?

**Comment by ChirayyuS** [comment]
I am experiencing same issue, I am not using Material-UI modal or any overlay components to load Plaid. but using `usePlaidLink`.
how to add/pass `trapFocus` / `disableEnforceFocus` ?

**Comment by alecherryy** [comment]
> usePlaidLink

Did you ever find a solution? I am running into the same issue.
