### ISSUE TITLE
Need to check condition for token

### ISSUE THREAD

**Issue by Mukesh-Quolum** [plaid/react-plaid-link#169]
https://github.com/plaid/react-plaid-link/blob/328b963a20758f611e6673dffc7bb9dc0c59a3a4/src/usePlaidLink.ts#L33

It'll be grate if you add the condition for if config.token is present or not. Because we generate this token asynchronously and we can't call the hook based on condition while using `usePlaidLink`.

**Comment by dillondrenzek** [comment]
Just curious why this was closed? I'm having a similar issue. Within our product, we call our own API to fetch a the link access token on a button click - is there a better way to do this?

**Comment by skylarmb** [comment]
@dillondrenzek See this feature request: https://github.com/plaid/react-plaid-link/issues/128

Here is my example for how to do this: https://github.com/plaid/react-plaid-link/issues/128#issuecomment-696354701
