### ISSUE TITLE
Question: How do I respond to user closing plaid after success?

### ISSUE THREAD

**Issue by tdeedlesATX** [plaid/react-plaid-link#181]
I have the following use case: 

Upon exiting any success screen (`onSuccess` has run), I'd like to be able to fire a callback to the user clicking the continue button or closer button on the success screens. Equivalently, this callback could execute when it is known that the UI is closed. Is there some 1st class way to know when user has closed the plaid UI, and it is no longer in view? Such as 

```
const {isOpen} = usePlaidLink(...)
```

I have highlighted in green what I might expect I should be able to respond to when UI is in a successful state after user closes. 

![image](https://user-images.githubusercontent.com/10747365/116149679-10b5d280-a6a8-11eb-8d9b-6e81e61eb554.png)

I'd love to know your recommendation before I go hacking. Thanks!

**Comment by tdeedlesATX** [comment]
I have since noticed that `onExit` does execute with a nullish `error` first argument which may satisfy my use case. Would this be the right approach?

**Comment by brandon-lile** [comment]
@tdeedlesATX you can pass a function with property `onExit` to `usePlaidLink`

```tsx
const onExit = useCallback(() => {
  console.log('exiting');
}, []);

const { open, ready, error } = usePlaidLink({
  token,
  onSuccess,
  onExit,
});
```

**Comment by skylarmb** [comment]
+1 to @brandon-lile! `onSuccess` fires when the success screen is visible. `onExit` fires when Link is closed. Check out what data you get back in the `onExit` callback here: https://plaid.com/docs/link/web/#onexit

**Comment by rubendinho** [comment]
Is there no way to intercept when a user, upon successfully linking an item, his "Continue" on the Success screen?

In our onSuccess callback, we update the cache to reflect that there is a new linked item, which can cause navigational events away from the page where Link is open.

**Comment by brandon-lile** [comment]
I'm guessing you're using a similar workflow to what we were using. Basically:
- `PlaidLink` exists in a rendered `Route`
- User adds a linked item, `onSuccess` is called, and context is updated
- The context update causes a redirect (or some other thing to cause the route to change)
- `PlaidLink` is torn down, causing the `onExit` to be called

If this is what's happening to you, we solved it by checking the metadata in `onExit`:
```tsx
const onExit = useCallback((error, metadata) => {
  if (metadata.status !== 'connected') {
    # This means onExit was called without completing an account link
  }
}, [])
```

**Comment by rubendinho** [comment]
Thanks, but that did not work. The `onExit` event is only firing AFTER the teardown, so before the user has a chance to close the widget and too late for the issue we're experiencing.

I was able to move our refetch/cache update to the `onEvent` callback, targeting the `HANDOFF` event.  This event gets invoked when no matter how the user exits PlaidLink after a successful connection.

**Comment by tdeedlesATX** [comment]
> HANDOFF event.

Thanks @rubendinho . I also received this same guidance you mention from the Plaid developer support. They also mentioned that this event name is guaranteed to be stable for this exact use case.

**Comment by tdeedlesATX** [comment]
[From link docs](https://plaid.com/docs/link/web/#onevent):

> The following onEvent callbacks are stable, which means that they will not be deprecated or changed: open, exit, handoff, selectInstitution, error. The remaining callback events are informational and subject to change, and therefore should not be used to customize your product experience.

**Comment by skylarmb** [comment]
Glad you were able to resolve this with the HANDOFF event. I'll bring this feedback to our docs team and see if we can clarify some of the documentation around this.

**Comment by tdeedlesATX** [comment]
@skylarmb could we add the stable event names as exports as part of the module for typescript? This will help with documentation and would alert developer (and maintaining team) to a break in this aspect of contract.

**Comment by tdeedlesATX** [comment]
>Glad you were able to resolve this with the HANDOFF event. I'll bring this feedback to our docs team and see if we can clarify some of the documentation around this.

I'm actually having issues trying to implement in this manner and only seeing events including the term "TRANSITION" when clicking the closer, or "continue" button on the screen in this issue's description.

**Comment by skylarmb** [comment]
@tdeedlesATX glad you were able to get it resolved with Luigi! The stable event names is a good idea! Is this what you mean? https://github.com/plaid/react-plaid-link/pull/195

**Comment by skylarmb** [comment]
@tdeedlesATX v3.2.0 which i just published has much better types for all of our Link events, including an exported type for these stable events if you want to use it! Check it out here https://github.com/plaid/react-plaid-link/blob/master/src/types/index.ts
