### ISSUE TITLE
Plaid Link is glitching and won't allow me do anything

### ISSUE THREAD

**Issue by TaylorFacen** [plaid/react-plaid-link#182]
https://user-images.githubusercontent.com/44216029/116497203-cafa3500-a874-11eb-9918-296b1723b65a.mov

I'm trying to use Plaid Link in my React app. I'm unable to easily type anything in the fields because the iFrame keeps rapid focusing on the back button at the top ( I had to press the keys multiple times to get them to type in the attached video). Any advice on how to fix? For reference, I'm using [Chakra](https://chakra-ui.com) as my component library. Not sure if any of its styling is causing an issue.

**Comment by skylarmb** [comment]
hi @TaylorFacen this looks like you might have a key stuck on your keyboard? I can reproduce this video exactly if i hold down the `Tab` key for example. Let me know if you were able to resolve this

**Comment by TaylorFacen** [comment]
Thanks for the response @skylarmb I actually don't have any keys stuck on my keyboard. I'm able to use Plaid Link on other websites that use the sdk just fine.

**Comment by skylarmb** [comment]
@TaylorFacen is there any way you could share some code that reproduces this?

**Comment by skylarmb** [comment]
@TaylorFacen does this solution to a similar issue solve your problem by any chance? https://github.com/plaid/react-plaid-link/issues/160#issuecomment-749621705

**Comment by TaylorFacen** [comment]
> @TaylorFacen does this solution to a similar issue solve your problem by any chance? [#160 (comment)](https://github.com/plaid/react-plaid-link/issues/160#issuecomment-749621705)

This fixed it! Thank you so much!
