### ISSUE TITLE
Skip Institution Picker And Go Straight To Login Page?

### ISSUE THREAD

**Issue by pihish** [plaid/react-plaid-link#184]
We're working with users who we know bank at a few specific institutions.  When initializing Link, is there anyway to programmatically skip the institution picker step by telling Link exactly what bank we want our user to login to?

If you look at this [image](https://plaid.com/_next/static/images/link-example-img-de1ddc63c137c151a770f74dffe1b73a.png.webp), I'd like to skip the left screen and go to the right screen (where Link asks for the username and password for an already selected institution).

**Comment by skylarmb** [comment]
Hi @pihish this is not supported, but thanks for the feedback!
