### ISSUE TITLE
usePlaidLink resets my component and redux States

### ISSUE THREAD

**Issue by Namit-Perkfix** [plaid/react-plaid-link#185]
I am using usePlaidLink in my functional component, and after open() from usePlaidLink(config), all the functional states and appContext states reset to the initial values. I have double checked and there is no code that is explicitly doing this from my side.

This is how I am using it:

`import React, { useCallback, useContext, useState, useEffect } from "react";
import { usePlaidLink } from "react-plaid-link";
import { AppContext } from "../../context/app/appContext";

export const MyOrgPaymentsPage = () => {
    const appContext = useContext(AppContext);
    const [newPaymentMethodBucket, setNewPaymentMethodBucket] = useState("licensing");

    const onSuccess = useCallback( (token, metadata) => {
        console.log("on Success", appContext, newPaymentMethodBucket);  // All the global and local states reset here
    }, []);

    const config = {
        clientName: "<NAME>",
        env: "sandbox",
        product: ["auth", "transactions"],
        publicKey: "<KEY>",
        onSuccess,
        // ...
    };

    const { open, ready, error } = usePlaidLink(config);

    return (
        <div>
            <div onClick = {() => {setNewPaymentMethodBucket('licensing')}} >Licensing</div>
            <div onClick = {() => {setNewPaymentMethodBucket('budget')}} >Budget</div>
            <button onClick = {() => open()}>
        </div>
    )
}`

**Comment by skylarmb** [comment]
Are you sure it's actually resetting the context? I think you are just seeing a stale value in the `onSuccess` function because your `useCallback` function has an empty array as the second argument, meaning you are explicitly evaluating `appContext` only once when the component mounts and never again. Try adding `appContext` and `newPaymentMethodBucket` to the dependency array in the `useCallback`. This is not an issue with `react-plaid-link` and is just the basics of how React works.

```jsx
  const onSuccess = useCallback((token, metadata) => {
    console.log("on Success", appContext, newPaymentMethodBucket);
  }, [appContext, newPaymentMethodBucket]);
  ```

https://reactjs.org/docs/hooks-reference.html#usecallback

> every value referenced inside the callback should also appear in the dependencies array

**Comment by skylarmb** [comment]
You also have some invalid HTML/JSX... your `button` element has no closing tag.

**Comment by Namit-Perkfix** [comment]
@skylarmb I have tried including the variables in the dependency array in useContext. It only prevents the first variable in the array from going back to the initial state, but pushes everything else back in the component to the initially mentioned state. So as per your example, if the dependency array looks like **[appContext, newPaymentMethodBucket]**, it would not reset my appContext but still reset everything else 'INCLUDING' **newPaymentMethodBucket**.
