### ISSUE TITLE
version 3.1.1 isn't accessible on npm

### ISSUE THREAD

**Issue by boertel** [plaid/react-plaid-link#192]
Command:
```
npm install react-plaid-link@3.1.1
```

Result:
```
npm ERR! notarget No matching version found for react-plaid-link@3.1.1.
```

Expected behavior:
install version 3.1.1

3.1.1 is missing from: https://www.npmjs.com/package/react-plaid-link

**Comment by skylarmb** [comment]
hi @boertel not quite sure what happened here but you are correct... it is not on there. Maybe our publishing script errored out. Either way, try installing 3.2.0 which was just published with much improved TypeScript types :)
