### ISSUE TITLE
How to get error information before link is closed?

### ISSUE THREAD

**Issue by ls-smock-recruit** [plaid/react-plaid-link#196]
Hi,

We are experiencing issues trying to support users using the link flow due to a flow on-effect of issue #139.
Periodically, users will experience errors when trying to link their accounts, particularly when using microdeposits which some people find confusing.
In order to assist these users we would like to be able to collect any information they experienced during their link flow, however, the error events are only fired once link is closed - the problem being is that users will often just not close link at all (especially on mobile devices), they will just close the entire tab/browser or just navigate away from their browser and contact us for support.

This leaves us somewhat in the dark. To compound this, Plaid support will not assist unless we provide a link or request id, but again AFAIK, these are obtained on the client side from the events as well.

Is there any other method to get Plaid error information if the user never gets through the flow to the point where they would send requests to our servers?
Alternatively, if there is no other way to get this information, I understand there might be some business reasons behind delaying link events, but would it possible to make an exception for errors events?

**Comment by skylarmb** [comment]
Hi @ls-smock-recruit. Link always immediately fires the `onEvent` callback with the `OPEN` event when it first initializes. This event contains a `link_session_id` so you can capture that no matter what the user does within Link.

If a user abandons the page before exiting Link (thus `onSuccess` or `onExit` never fire), you can search the `link_session_id` in the dashboard under the [Logs](https://dashboard.plaid.com/activity/logs) page, and all the logs for that session will appear there. You can also search the Logs page by `client_user_id` that was supplied to the `/link/token/create` call so you don't even need to know the `link_session_id` if you fail to capture it. Here is an example of an error I triggered an then closed the tab without exiting Link:


![image](https://user-images.githubusercontent.com/7543705/122125030-f0bba900-cde4-11eb-92b2-5a5c366194e9.png)

**Comment by skylarmb** [comment]
If this does not solve your use case feel free to chat with [Plaid support](https://dashboard.plaid.com/support)!

**Comment by ls-smock-recruit** [comment]
@skylarmb Thanks for getting back to me on this, appreciated - will forward this info on.
