### ISSUE TITLE
Error fires onExit callback after successful handoff event

### ISSUE THREAD

**Issue by kpermenter** [plaid/react-plaid-link#204]
I'm currently getting an error from the onExit callback saying that credentials are required to link an item to Plaid after the onSucess callback has been fired. The onSuccess function successfully hits my endpoint on submit and connects the account when fired, but the onExit function is always executed after. I need to figure out why I'm getting an error when everything seems to be working as expected.  I'm guessing that I'm missing something so any help would be appreciated!

`const PlaidLink = ({ token, getActiveView, getAccounts }: Props) => {
  const connectAccount = (account: any) => {
    return useApi('/v1/expense/payments/accounts/connect', 'POST', account).then((response) => {
      if(response) {
        getAccounts(0, 2).then(() => {
          if(account.length !== 0) {
            getActiveView('LIST');
          } else {
            getActiveView('LOADER');
          }
          return response;
        });
      };
      return response;
    });
  };

  const onSuccess = useCallback(
    (public_token, metadata) => {
      connectAccount({
        accounts: [
          {
            id: metadata.account.id,
            mask: metadata.account.mask,
            name: metadata.account.name,
          },
        ],
        institutionId: metadata.institution.institution_id,
        institutionName: metadata.institution.name,
        publicToken: metadata.public_token,
      });
    },
    [],
  );

  const onExit = useCallback(
    (error, metadata) => {
      console.log(error, metadata);
    },
    [],
  );

  const config: PlaidLinkOptions = {
    token,
    onSuccess,
    onExit,
  };

  const { open, ready } = usePlaidLink(config);

  return (
    <>
      {ready ? open() : null}
    </>
  );
};

export const Link = (props: Props) => {
  const [token, setToken] = useState<string | null>(null);

  const getAccountLink = () => {
    return useApi('/v1/expense/payments/accounts/link').then((response) => {
      if (response && response.linkToken) {
        setToken(response.linkToken);
      } else {
        return;
      };
    });
  };

  // generate a link_token
  useEffect(() => {
    getAccountLink();
  }, []);

  // initialize Link modal
  return token === null ? (
    <Loader />
  ) : (
    <PlaidLink
      token={token}
      getActiveView={props.getActiveView}
      getAccounts={props.getAccounts}
    />
  );
};
`

**Comment by skylarmb** [comment]
hey @kpermenter what is the value of the `error` and `metadata` when this extra `onExit` is called?

**Comment by marcaaron** [comment]
Seeing this same behavior. For what it's worth, we have not made any changes to the library version.

```
{
    "exitError": null,
    "metadata": {
        "institution": {
            "name": "Chase",
            "institution_id": "ins_3"
        },
        "request_id": "udt0ePvX7t2dJoC",
        "link_session_id": "a616154a-7c89-4a4e-882a-9b822506a6e5",
        "status": "connected"
    }
}
```

**Comment by skylarmb** [comment]
closing due to no response, feel free to re-open if you can still reproduce this and provide more details
