### ISSUE TITLE
CORS error for https://sandbox.plaid.com/link/client/get

### ISSUE THREAD

**Issue by Sergei-Karpuk98** [plaid/react-plaid-link#205]
Use React+Next

**Comment by skylarmb** [comment]
Hi there, CORS issues are an issue with your application. Your own app server or CDN configuration determines your CORS policy. 

You need to add
```
connect-src 'self' https://sandbox.plaid.com https://development.plaid.com https://production.plaid.com;
frame-src 'self' https://cdn.plaid.com;
style-src 'self' 'unsafe-inline';
```
to your CORS policy for your application. 


**This is not an issue with react-plaid-link.**
