### ISSUE TITLE
Calling open() for a second time does not bring up the modal, it stays loading

### ISSUE THREAD

**Issue by miguel-amaton-sp** [plaid/react-plaid-link#206]
Hi!

We're running into an issue where, when you close (using the integrated X button on the modal) or when you succesfully connect an account, and you try to call `open()` one more time, the modal does not open and remains loading.

On the network tab, it seems we do a single call to `heartbeat` (which the returns the same value as the first execution) but no subsequent call to `start`, and the `#iframe` remains empty.

Our environment is currently running on version `3.2.0`. I'm not sure what log information I make it easier to deduce this issue.

Thanks!

**Comment by moimikey** [comment]
network tab shows `start` getting called on plaid.com and this result:

```
{display_message: null, documentation_url: "https://plaid.com/docs/?ref=error#invalid-request-errors",…}
display_message: null
documentation_url: "https://plaid.com/docs/?ref=error#invalid-request-errors"
error_code: "INVALID_FIELD"
error_message: "oauth uri does not contain a valid oauth_state_id query parameter"
error_type: "INVALID_REQUEST"
request_id: "..."
```

**Comment by moimikey** [comment]
da-ha... you need to not pass `receivedRedirectUri` to the config unless you're going to use OAuth and configure it correctly. works when you kill that property.

**Comment by Mshakaa-CS** [comment]
I am also seeing the same issue any idea how to fix it?
@skylarmb

**Comment by moimikey** [comment]
ditto

**Comment by skylarmb** [comment]
hi @miguel-amaton-sp @moimikey @Mshakaa-CS Im am trying to reproduce this, but so far have been unable. Is there any details you could share about your implementation that might differ from a standard integration? 

Here is the test code I used to record this video: https://github.com/skylarmb/playground-react-plaid-link/blob/sb-debug-206/src/App.tsx


https://user-images.githubusercontent.com/7543705/131392485-b90a0968-9a49-4f49-8be0-23dab2949c4d.mp4
