### ISSUE TITLE
Plaid artifactory not responding

### ISSUE THREAD

**Issue by pjelar** [plaid/react-plaid-link#208]
Hi,

I'm trying to follow the instructions to checkout and install this module.

`yarn add react-plaid-link`

This fails with:
`getaddrinfo ENOTFOUND artifact.plaid.io`

Checking the dns it seems like that entry doesn't exist
```dig @8.8.8.8 artifact.plaid.io

; <<>> DiG 9.10.6 <<>> @8.8.8.8 artifact.plaid.io
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 64020
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;artifact.plaid.io.		IN	A

;; AUTHORITY SECTION:
plaid.io.		899	IN	SOA	ns-1315.awsdns-36.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 49 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Aug 24 18:40:48 BST 2021
;; MSG SIZE  rcvd: 131```

**Comment by skylarmb** [comment]
hey @pjelar do you have some special registry config set? this package is published publicly on yarnpkg.com and npmjs.com, so not sure how you are getting pointed to artifact.plaid.io to resolve this package. What repository are you installing this in?

https://classic.yarnpkg.com/en/package/react-plaid-link
https://www.npmjs.com/package/react-plaid-link

**Comment by skylarmb** [comment]
ah i see, a bad change was merged to `yarn.lock`... I will take care of this

**Comment by skylarmb** [comment]
@pjelar try the latest stable version, 3.2.1. I think this should be fixed

**Comment by pjelar** [comment]
Ok thanks will give it a go. 

Was just trying from your repo.
