### ISSUE TITLE
```flink.js:2 TypeError: Cannot read property 'rendering_property_key' of null``` on development

### ISSUE THREAD

**Issue by emekanw** [plaid/react-plaid-link#213]
Started getting this error on development today but works on production.

```flink.js:2 TypeError: Cannot read property 'rendering_property_key' of null```

**Comment by gricha2380** [comment]
We are seeing the same issue in our dev environment as well. 
```
flink.js:2 Uncaught (in promise) TypeError: Cannot read property 'rendering_property_key' of null
```

It happens somewhere between creating a link token and setting an access token. The error shows as coming from `flink.js` hosted `https://cdn.plaid.com/link/2.0.1143/flink.js`

**Comment by gricha2380** [comment]
The issue resolved itself for us over a month ago. We were in communication with Plaid support at the time, but they seemed not to know what was going on. We also haven't noticed any subsequent instances of the problem.

**Comment by skylarmb** [comment]
sounds great, we have monitored this internally and noticed it self resolve as well, may have been a transient issue.
