### ISSUE TITLE
Feature Request: Add ability to force mobile responsive view or customize width on desktop

### ISSUE THREAD

**Issue by marcaaron** [plaid/react-plaid-link#216]
Running into an interesting problem here where our preferred design when using Plaid link would be to have the modal appear in a specific location on screen e.g. this is the view we are trying to achieve in our new Expensify app:

![2021-09-27_14-54-27](https://user-images.githubusercontent.com/32969087/135004786-18e56b9a-4c14-462d-be9d-6f1b94cfe237.png)

However, the underlying styling for the Plaid Link UI is happening inside an iframe and we cannot modify these styles. We managed to get around this by ditching `react-plaid-link` in favor of another iframe loading the regular JavaScript sdk, but it's not very ideal and also looks more like this than the desired look:

![2021-09-27_14-57-12](https://user-images.githubusercontent.com/32969087/135004970-5641134b-6692-4b07-a783-7b9ae6f8b690.png)

Is there any suggestion for how to work around this limitation? Are the mobile responsive views returned when using a mobile user agent and not based on parent screen width? Assuming that is the case here and what prevents us from customizing this further.

It would be great if we could:

1. Force the mobile responsive view somehow
2. Add more options to customize the width + shadow of the Plaid UI

This view works great for us on mobile web, but creates a jarring experience for our desktop users.

**Comment by skylarmb** [comment]
hey @marcaaron, this is an interesting request. There may be some ways to hack around the iframe styling (as you experimented with in the linked PR) but I don't recommend it. Either way `react-plaid-link` is not going to support this so I am going to close this issue.
