### ISSUE TITLE
Wrong/Misleading metadata status

### ISSUE THREAD

**Issue by alexgtn** [plaid/react-plaid-link#218]
Hi,
Current behavior:
When clicking on the "X" button during institution select, I get the following metadata with "institution_not_found".
This is the same behavior as clicking on the custom close btn that I customised to display "Proceed to wire transfer".
```
{
"institution": {},
"request_id": null,
"link_session_id": "70cfce65-0936-4ee7-b63f-16777d1de7e2",
"status": "institution_not_found"
}
```
![](https://i.imgur.com/IF0kxnw.png)
![](https://i.imgur.com/HztYJd8.png)

Wanted behavior:
- clicking on X status: "closed_when_selecting_bank"
- clicking on the button "institution_not_found"

Is this a bug?

Best,
Alex

**Comment by skylarmb** [comment]
hey Alex, I definitely see why distinguishing between these two might be helpful. Its unlikely we could change the `exit_status` key here as this event is a ["Stable event"](https://plaid.com/docs/link/web/#onevent) but what we might be able to do here is provide some more helpful data in the metadata such as populating `instituion_search_query` and `view_name` in the `onEvent: EXIT` callback (so you can at least tell if the user was on the search results screen when exiting). I noticed that these fields are currently `null` in the metadata object which I am not sure is a bug or intended. I have filed a ticket to look at this. In the meantime until that is fixed you could look for the `onEvent: SEARCH_INSTITUTION` event to determine if the user searched for institution before exiting if that helps at all.

**Comment by skylarmb** [comment]
hi @alexgtn i brought this up internally at Plaid and got some pushback on changing this behavior or callback API. This API is very stable and it is important we keep it that way for backwards compatibility across all of our customers, so it is unlikely we are going to change anything here, sorry.
