### ISSUE TITLE
receivedRedirectUri parsing error

### ISSUE THREAD

**Issue by thierry1129** [plaid/react-plaid-link#219]
Hi, 

When I'm trying to enable oAuth in our plaid flow, I am consistently seeing this error no matter whether I pass in raw or encoded urls. This happened after link-token has been successfully fetched and before client side plaid.open() trigger, and the request url is https://sandbox.plaid.com/link/client/get.

```    
const plaidConfig = {
    clientName: metadata.get('appName'),
    env: config.get('env') === 'production'
      ? 'production'
      : 'sandbox',
    language,
    onExit,
    onSuccess,
    product: ['auth'],
    receivedRedirectUri: encodeURIComponent(global.window.location.href),
    // receivedRedirectUri: encodeURI(global.window.location.href),
    // receivedRedirectUri: global.window.location.href,
    token: linktoken,
  };
const plaid = usePlaid(plaidConfig);
```

- plaid api version: 2020-09-14
- react-plaid-link version: 3.2.1
- environment: sandbox. 
- link-token: configured with redirect_uri properly set on the server side. 
- receivedRedirectUri:  same as redirect_uri when generating link-token, and set in plaid dashboard, http://localhost:3000/appname/eplata/orgname/eplata/wallet/banks/link/plaid
![mr7ENTVrHrjTNjZ](https://user-images.githubusercontent.com/18585160/145265879-1cff33eb-0226-4950-81f1-7cfc4070d553.png)
![ORfOlRel33GNhnj](https://user-images.githubusercontent.com/18585160/145265881-d40cab5e-bbfc-4455-9bcd-fafd5d52d43c.png)
![errmsg](https://user-images.githubusercontent.com/18585160/145267202-18d5231d-f977-442d-a5ca-36d48d2678d2.png)

The error msg is telling me to 'URI escape' the string, I'm not sure why it still doesn't like it after wrapping it in encodeURIComponent

**Comment by skylarmb** [comment]
hi @thierry1129 it looks like you may not be be capturing the query string properly, which contains the required `oauth_state_id` parameter. Are you doing a client-side redirect or something else that is discarding the query string?

If you create a `link_token` with `https://example.com/foo/bar` as the `redirect_uri`, Plaid should send your users back to `https://example.com/foo/bar?oauth_state_id=bf54ed8f-ceea-4bcb-a0ca-2afa3fd5ee35` for example. You need to pass this full URI including the query string in the `received_redirect_uri` and in your screenshots it appears you are not doing that. Does that help at all?

**Comment by thierry1129** [comment]
hey @skylarmb Thanks for the explanation! Yeah i was confused about the receivedRedirectUri param and I think I got it now. Closing
