### ISSUE TITLE
`PlaidLinkOnSuccessMetadata` type missing `account` object

### ISSUE THREAD

**Issue by tomislavhrenmp** [plaid/react-plaid-link#220]
Hi Plaid team,
I just bumped the `react-plaid-link` version to `3.2.1`
and when I look at the `PlaidLinkOnSuccessMetadata` type,
there's only the `accounts` object,
but if I log metadata from the `onSuccess` callback,
I can also see the `account` object.

![image](https://user-images.githubusercontent.com/89005117/146193094-df270fe9-9095-49e4-826d-b71ea30a0e9b.png)

**Comment by iampava** [comment]
+1

We have the same issue. It seems the TS definitions are not in sync with what's actually returned: https://github.com/plaid/react-plaid-link/blob/master/src/types/index.ts#L24-L28

**Comment by skylarmb** [comment]
Hi there all, `account` was deprecated a long time ago and should not be used as it cannot properly represent the case where a user selects multiple accounts (if that is enabled [here](https://dashboard.plaid.com/link/account-select)). It is included in the callback to maintain backwards compatibility only. Please use `accounts` instead

https://plaid.com/docs/link/web/#link-web-onsuccess-metadata-account
