### ISSUE TITLE
Error while loading async token

### ISSUE THREAD

**Issue by davidsonsns** [plaid/react-plaid-link#223]
On the application I'm working on, we're loading the public token asynchronously. So, every first render we're facing the following error: `Error loading Plaid null` (which lands [here](https://github.com/plaid/react-plaid-link/blob/d6756c190aa33a244a22ae3619f8ea385cee5b5f/src/usePlaidLink.ts#L39)).

The error is self-explanatory, we're getting it because at the first moment we don't have the token, ok. So, why `token` is a [non-required field](https://github.com/plaid/react-plaid-link/blob/d6756c190aa33a244a22ae3619f8ea385cee5b5f/src/types/index.ts#L22)?

**Comment by davidsonsns** [comment]
ok, closing this one cause i found this another one: https://github.com/plaid/react-plaid-link/pull/197

**Comment by skylarmb** [comment]
hey @davidsonsns this was resolved in v3.2.2 which was published today
