### ISSUE TITLE
Webhook prop not being passed through?

### ISSUE THREAD

**Issue by sarink** [plaid/react-plaid-link#225]
React, the `webhook` prop is set correctly:
<img width="618" alt="Screen Shot 2022-01-25 at 10 12 46 AM" src="https://user-images.githubusercontent.com/1881761/151014815-467106c6-a3b2-43ad-a664-c45fee2d7a72.png">

Network create call (showing `payload.options.userConfig.webhook` is null)
<img width="528" alt="Screen Shot 2022-01-25 at 10 11 13 AM" src="https://user-images.githubusercontent.com/1881761/151014551-8fe1aa38-21b1-4204-a1ac-774d31e4365d.png">

**Comment by rubendinho** [comment]
@sarink - the webhook is set as part of your Link Token creation, not passed in as a prop. https://plaid.com/docs/api/tokens/#link-token-create-request-webhook

**Comment by sarink** [comment]
Hmm. That's confusing :-| 
<img width="819" alt="Screen Shot 2022-01-25 at 10 34 58 AM" src="https://user-images.githubusercontent.com/1881761/151019052-1d5edcea-bf36-4373-8e37-161692432e94.png">

1. Initialize `<PlaidLink>` component
2. User goes through link flow
3. `PlaidLink.onSuccess` receives a `publicToken`, send this to your server
4. On the server, take the public token and call `plaid.itemPublicTokenExchange`
5. Now you have an access token, use this to retrieve an item, via `plaid.itemGet`

@rubendinho can you tell me what I'm doing wrong?

**Comment by rubendinho** [comment]
I believe previous versions of this package supported passing in a webhook as a prop (and might still support it, i'm not sure), before `linkTokens` became the preferred way of configuring Link. 

Since you're using `linkToken`, the webhook must be set on the server-side request where you're generating the `linkToken` from Plaid.
