### ISSUE TITLE
Is it possible to restrict the list of financial institutions displayed in the Plaid widget?

### ISSUE THREAD

**Issue by azinod** [plaid/react-plaid-link#234]
Hello,

We have got this requirement to restrict/filter the list of financial institutions (aka banks) that can be displayed to the user in the Plaid widget _(check screenshot at the end of the post for reference)_.

## Our question:
Is there a way to accomplish this by changing some setting, enabling a flag, or any other way?
<br>

### What we tried so far:
- Change settings in the developer portal to change the Financial Institutions that are presented ([as in the documentation](https://plaid.com/docs/link/customization/#financial-institutions)), however this just changes the initial list that is displayed, users are still able to input any bank name and get them to display... we need to restrict the items that can actually be displayed to the user;
- We also tried to listen to the events triggered by the Plaid widget and then somehow try to intercept and change the list of items that are displayed, but the developer that worked on it reported that the events are triggered only when the Plaid widget is closed, not as they happen;

### What we did not try yet (and wanted to avoid):
- Analyse network tab to identify API calls performed by the Plaid widget and try to replicate it with our own UI, where we would filter the items we need to restrict;

<br>

_Screenshot for reference: bank/financial Institution selection list_

![image](https://user-images.githubusercontent.com/16745297/152443732-951afdbc-d961-4093-9c0f-90206c9e57de.png)

**Comment by azinod** [comment]
PS: I know the `react-plaid-link` package just injects the `plaid link web script` into the page and creates a wrapper around it, but there does not seem to be a public repository for the web script, so I opened the PR in this one.

If this is something that is not possible at this moment, I am happy to take a look at it and push a PR adding the feature if you guys help me set up the repository to do so.

**Comment by madgbec** [comment]
Properties too expensive his is all bad

**Comment by skylarmb** [comment]
Hi @azinod. The primary way of filtering institutions in Link is through what `products` you supply to the token create call. Which products you are using determines which institutions show up in Link searches. It is intended for all institutions that are compatible with your specified `products` to be available to users in Link.

https://plaid.com/docs/link/best-practices/#choosing-when-to-initialize-products

> If this is something that is not implemented or possible at the moment, I would be happy to take a look at it and push a PR adding the feature if you guys think it is feasible and help me set up the repository to do so.

I appreciate the desire to contribute, but as mentioned, this is desired/expected behavior and this repo does not actually have anything to do with the functionality of Link itself.
