### ISSUE TITLE
Manual microdeposits loop

### ISSUE THREAD

**Issue by simsketch** [plaid/react-plaid-link#237]
Users trying to verify Manual MDs are sent in a loop where they are unable to verify the MD once they have received them...they get asked to initiate microdeposit again. We are using the same day microdeposit flow.

This happens intermittently for our users. Have you had anyone else running into this issue? We don't have a whole lot of visibility into the issue because it seems to be happening on the plaid end. We are using `react-plaid-link` version 3.0 but we can upgrade to 3.3.0 if you think it might help our issue?

We've reached out to Plaid support and they agree that it is most likely an issue with `react-plaid-link` and not on our end. The integration has been working for a couple of years and there haven't been any code changes related to it on our end.

**Comment by madgbec** [comment]
I'm having theft issues from  Facebook systems hackers put me on a 2 decimal limit with exchanging through code commas 4 decimals then rerouting all my money elsewhere. I think they've stolen 8 properties rocket mortgage notices seeN Twitter

**Comment by madgbec** [comment]
It appears my computer or devices have been modified to not react properly, not notice things while using my account to collect god knows how much of my money.

**Comment by skylarmb** [comment]
hi @simsketch I dont think this is an issue with the `react-plaid-link` SDK. For context, this repo is just a tiny wrapper around our [vanilla JS code](https://plaid.com/docs/link/web/) and contains no business logic or UI code. It sounds like the issue your users are running into is either something within the Link experience itself, not a bug in this wrapper.

I know this is not a satisfying answer, but I would encourage you to follow up on your support ticket again to try to gain more clarity. If you tell me your specific ticket number I can make sure someone more familiar with MMD flows follows up on it for you.
