### ISSUE TITLE
Error occurs when clicking on Try Again button

### ISSUE THREAD

**Issue by arungogosoon** [plaid/react-plaid-link#244]
### Steps to re-produce

1. Link a bank account form plaid sandbox
2. Make the account status to INVALID_UPDATED_USERNAME
3. Try to re-authenticate this account in update mode
4. provide username / passcode: user_good / pass_good, then provide OTP as 1234 and go to last step
5. It shows message saying "Incorrect username" , now click on Try Again button.

Plaid loader wraps up entire screen.

NOTE:
1. while trying to get item information using plaid-sdk it says 'ITEM_LOGIN_REQUIRED' instead of 'INVALID_UPDATED_USERNAME'

![image](https://user-images.githubusercontent.com/77015668/158868322-5798661d-0ba5-440b-aa71-be5dc21f350a.png)

**Comment by skylarmb** [comment]
hi @arungogosoon thanks for the report. Two things here.
- First, this is not an issue with `react-plaid-link` itself (this repo is just a little react wrapper around our standard Javascript SDK). This appears to be an issue within Link javascript code itself. 
- Second, the stack trace for this indicates to me this is from some legacy code that is going to be replaced very shortly. This rollout has already happened in production, but we have not rolled it out to sandbox yet.

Thank you for the report! I can send an update here once we roll out the change to sandbox so you can test this same scenario.
