### ISSUE TITLE
institution_not_found event isn't thrown after returning to the bank select screen 

### ISSUE THREAD

**Issue by jjjding2** [plaid/react-plaid-link#251]
After deploying to prod, I came across an inconsistency between the sandbox and production environment. Steps to reproduce:
1. Open Plaid
2. Select an institution
3. Click the back arrow to return to the institution list
4. Exit

In onExit, the exit_status is `institution_not_found` in Sandbox as expected, but in production the exit_status is either `requires_oauth` or `requires_credentials` depending on the institution you returned from. This incorrect exit_status is also returned when you click "Link Manually" in the institution select screen. Without the `institution_not_found` status on exit, our web app immediately closes the modal instead of handing off to manual verification.

I don't think the behavior upon exiting Plaid on the select institution screen should depend on the bank account the user is returning from. The inconsistency between sandbox and production is also worrying because we weren't able to catch this issue before deploying.

**Comment by jjjding2** [comment]
Also, I'm on version 3.3.0

**Comment by jjjding2** [comment]
After some more testing, this bug is also surfacing in Sandbox for OAuth, but not the other institutions that just require credentials

**Comment by skylarmb** [comment]
Sorry for the late response here @jjjding2, can you confirm if you are still seeing this behavior? I was not able to reproduce it given your steps here. I always receive `requires_credentials` both in sandbox and prod.

I only see `institution_not_found` if I perform a search that triggers the "no results found" screen, or if I simply close after performing any search without clicking an institution.

If you are still seeing this issue, can you open a ticket with Plaid support (https://dashboard.plaid.com/support) with some example link session IDs where you encountered this? You can mention this github issue in your ticket.

**Comment by jjjding2** [comment]
If the behaviour you described is intended then this shouldn't be an issue. 

When I opened the ticket I thought that the problem _was_ that we receive `requires_credentials` on the account select screen after clicking an institution instead of `institution_not_found` as you described.

**Comment by skylarmb** [comment]
gotcha, I will double check on this internally thanks! I am actually not 100% sure myself if this is intended or not.

Either way, whatever the behavior is it should be consistent between prod and sandbox. If that is not the case, that would be a more serious issue.
