### ISSUE TITLE
Make `PlaidLink` completely unaware of children visual properties

### ISSUE THREAD

**Issue by rafaelrinaldi** [plaid/react-plaid-link#26]
Right now `PlaidLink` passes down some styling to its children by default. In order to overcome that one must pass down an empty object as `style`.
In my opinion it would make more sense if `PlaidLink` didn't care at all about what's being rendered.

If you do agree I can send a PR that makes this possible.

Thanks.

**Comment by pbernasconi** [comment]
👍 I think you're right @rafaelrinaldi – feel free to create a PR and I'll try and review it promptly

**Comment by rafaelrinaldi** [comment]
Great to hear! Feel free to assign this one to me.

**Comment by rafaelrinaldi** [comment]
@pbernasconi Just sent #27.

While working on this I also have noticed that we don't really have tests and that many libraries are outdated. It seems like a low hanging fruit to me, let me know if you want me to tackle that separately if you find it valuable.

**Comment by jakubste** [comment]
@pbernasconi any progress on this? I just wasted some time custom-styling button for Plaid, because of not having the ability to use Button from Material UI. I think it's frustrating for a lot of people.

**Comment by pbernasconi** [comment]
This should be fixed now in https://github.com/plaid/react-plaid-link/pull/81/

`v2.0.0` was just released, so please test it out by checking the updated `README` and let me know!

There's also a storybook to test using Hooks and the Component wrapper: 

https://plaid.github.io/react-plaid-link
