### ISSUE TITLE
You may need to update your app in order to connect to Chase.

### ISSUE THREAD

**Issue by baharalidurrani** [plaid/react-plaid-link#270]
I'm getting this message from my Plaid SandBox and some of my production users.

> You may need to update your app in order to connect to Chase.

I've upgraded the following libraries to their latest versions but still no luck.

## Versions:
[`plaid`](https://www.npmjs.com/package/plaid) (plaid-node): `10.8.0` (latest as per today)
[`react-plaid-link`](https://www.npmjs.com/package/react-plaid-link): `3.3.2` (latest as per today)

## Screenshot
<img width="366" alt="Screenshot 2022-08-04 at 01 14 17" src="https://user-images.githubusercontent.com/33373727/182701926-4b2561e9-8989-45af-9fa7-04ab747d5714.png">

**Comment by phoenixy1** [comment]
Given that the institution in question in Chase, I suspect this is an OAuth issue. Have you gone through all the OAuth enablement steps? 
https://plaid.com/docs/link/oauth/

**Comment by baharalidurrani** [comment]
I'm afraid not, do I have to implement it for Desktop Web too? I thought that was for mobile apps.

**Comment by phoenixy1** [comment]
For desktop web, you don't need to do the work of setting up client redirects in your code, but you *do* need to fill out the various forms and agreements in order to be enabled for Chase OAuth (https://dashboard.plaid.com/team/oauth-institutions) so that Plaid has permission from Chase to use the Chase API on your behalf.

**Comment by discover59** [comment]
Is this issue fixed and released?

**Comment by phoenixy1** [comment]
@discover59 this is not a bug in the SDK (as far as we know), it is an error resulting from not having fully completed the OAuth registration steps to enable Chase OAuth for your Plaid `client_id`. More info on these steps can be found on the dashboard: https://dashboard.plaid.com/team/oauth-institutions and in the oauth docs.

**Comment by discover59** [comment]
Thank you for your clarification, @phoenixy1 !
