### ISSUE TITLE
Handle OAUTH_STATE_ID_ALREADY_PROCESSED error

### ISSUE THREAD

**Issue by xyzzyxyzzy0077** [plaid/react-plaid-link#272]
I'm wondering what is the recommended way to handle oauth error like `OAUTH_STATE_ID_ALREADY_PROCESSED` error, which could happen simply because users refresh the redirected page. 

Currently I'm only seeing a console error `Error: oauth_state_id has already been processed and deleted.` coming from the popup, while the `error` from the hook still being `undefined`. If I want to catch the error and let the user know what's wrong, what would be the way to do it?

**Comment by rubendinho** [comment]
@xyzzyxyzzy0077 you could consider caching the processed `oauth_state_id` in localStorage upon a successful OAuth flow completion, and render the standard Plaid Link widget if the user reloads the page.

**Comment by xyzzyxyzzy0077** [comment]
That sounds good. Thanks for the advice.
