### ISSUE TITLE
App2 Web Oauth Issue

### ISSUE THREAD

**Issue by shinazcodes** [plaid/react-plaid-link#275]
I am linking a bank account mid-onboarding flow in my application using react-plaid-link.
When plaid launches an App2App bank linking scenario it opens a new tab in the browser once the user completes the App2App flow and hence I am not able to continue my onboarding flow, since I don't have the session data in the new tab. 
I have provided the proper linkToken and also implemented redirectUri and receivedRedirectUri tags and it works correctly when the oauth is successfully done within the browser, but not when it opens another bank's app like Chase.

Is there a way to force the oauth to be done within the webview/browser tab rather than being taken to a separate app.
Or is there a way to help me maintain the onboarding session without having to store the onboarding data in an unsafe local storage, like can I provide a token from my side while creating the linkToken which can be sent back to me along with the oauth_state_id query to resume my onboarding session.

**Comment by phoenixy1** [comment]
Closing this out, as app2app OAuth redirect behavior has changed substantially since this issue was originally filed. To answer the question as asked, though, it is not possible to disable app2app redirects.

**Comment by ketul-capsync** [comment]
what was the solution ? I am still facing this issue.

**Comment by ketul-capsync** [comment]
Hi @phoenixy1, 
I am using a web app and using hosted link for the redirection, implemented properly the redirect_uri and receivedRedirectUri, it works perfect with the user agent of nexus 5 from the official documentation. 

user agent: "Mozilla/5.0 (Linux; Android 5.1.1; Nexus 5 Build/LMY48B; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.65 Mobile Safari/537.36"

It works perfectly fine with sandbox environment for First Platypus Bank - Oauth app 2 app.

While on production it is causing issue for Chase Institution it does not redirect to the given URI but shows blank page in the browser, I also understand that Chase does take time in the approval process but all has been done fine.

Is there something I am missing ? why does it not redirects to the desired uri.

I am using react + node for my web app.

Also can you guide me if This has been solve in the plaid pattern github repo and what page or code to look at exactly ?

Mine oauth_state_id and redirection works perfectly on sandbox environment even for chase and also First Platypus bank - Oauth app2app flow.

Thank you.
