### ISSUE TITLE
How to test local-app with redirect url 

### ISSUE THREAD

**Issue by itzzshirlayyy** [plaid/react-plaid-link#281]
I have a locally running react native app on my desktop and I would like to test that the redirect works . I saw that the documentation now says on desktop it will always open a new window regardless. But for the sake of testing my redirect flow, I would like to test it against desktop. Any way to do that?

**Comment by itzzshirlayyy** [comment]
@phoenixy1  @skylarmb If you can help provide any assistance on this that would be great! Thank you!

**Comment by phoenixy1** [comment]
Closing this out, but for posterity this is documented in the oauth docs at https://plaid.com/docs/link/oauth/#testing-oauth
