### ISSUE TITLE
"You may need to update your app in order to connect to Chase." in dev environment (not OAuth)

### ISSUE THREAD

**Issue by csku** [plaid/react-plaid-link#282]
I am getting the same error as in #270 . I am not using OAuth at all, and this is coming from the development endpoint. I was able to successfully update the link token using this method until a month or two ago.

I am using plaid-python v7.5.0 which is not the latest version but is the latest version that is not auto-generated. Has support for this been suspended?

**Comment by phoenixy1** [comment]
The issue is that Chase no longer supports non-OAuth-based access, which is why you're hitting an error. At this time, you are required to use OAuth-based connections to connect to Chase. There is no requirement to upgrade your client library but you will need to follow the OAuth registration steps and other steps in the OAuth docs.

**Comment by phoenixy1** [comment]
That is correct. However, one requirement for OAuth registration is being enabled for Production access. Once you have Production access, you don't need to use it and can continue to connect from Development, but you do need to be Production-approved in order to connect to Chase.

**Comment by csku** [comment]
Got it, thank you very much.

**Comment by discover59** [comment]
@phoenixy1 Does it mean that I have to apply "Production Environment" to use all Oauth-based bank integrations?

**Comment by csku** [comment]
I believe that is correct - you have to be Production approved to use OAuth, with the exception of Bank of America.

I requested Production access yesterday, and was told to continue using Dev until I was "ready to scale". I've written back but don't know if Production access will be granted.

**Comment by csku** [comment]
Update for anyone who encounters this in the future:

 - I was granted production access. I had to complete a security questionnaire, which was understandably geared towards companies, but I answered it using my personal security practices as best as possible.
  - Enabling Chase involves further diligence. It involved no further steps on my end, but it took a further 2-3 weeks for access to Chase.
