### ISSUE TITLE
Plaid link never gets ready

### ISSUE THREAD

**Issue by allroundexperts** [plaid/react-plaid-link#285]
Facing this issue intermittently. It seems like the issue is in `react-use-scripts`. I have created a bug ticket at there end as well: https://github.com/hupe1980/react-script-hook/issues/35

Reading there implementation, I feel like it will take a while that they'll fix it properly. Maybe we should move to another library?

**Comment by adnanlazer** [comment]
Facing the same issue. Have you found any solution in the meantime? or any previous version without this issue?

**Comment by FourLineCode** [comment]
Facing the same issue. Have you found any solution in the meantime? or any previous version without this issue?

**Comment by nikhilpsathyanathan** [comment]
I couldn't start a session from a modal

**Comment by sneacy** [comment]
Any movement from Plaid on this? Starting to see this issue sporadically for customers. It seems to work fine after refreshing the browser, but this isn't a great UX. This is almost impossible to reproduce consistently enough to try to implement a workaround in our own app code.

**Comment by sarthak-arora1997** [comment]
I am facing the issue where the button is not ready from the get go itself !! Have been stuck for days, please help !!

**Comment by nikhilpsathyanathan** [comment]
I had similar issues, I was't able to open from a modal so i passed the function from a page to modal as a prop and it worked.
I don't why it's behaving weirdly .
@sarthak-arora1997  It may help you

**Comment by sarthak-arora1997** [comment]
@nikhilpsathyanathan which function did you pass ? was it the one that creates the link_token ? I am calling the create_link_token using axios.post in my App.js file and then storing that token in a useState variable which I pass on to as a prop to the below route:
     <Route exact path="/office/diagnostic/finance/profitability/plaid_link" element={<Link token = {token}/>} />
The Link functional component uses the react-plaid-link:
`    console.log(props.token)
    const { open, ready } = usePlaidLink({
        token: props.token,
        onSuccess: (public_token, metadata) => {
            console.log("success",public_token,metadata)
          },
      });
    console.log(ready)
    return (
        <button onClick={() => open()} disabled={!ready}>
          Open Link and connect your bank!
        </button>
    );
  }
`

**Comment by nikhilpsathyanathan** [comment]
I have called the usePlaidLink hook in the page level 
and passed open as a prop

**Comment by VolodymyrHry** [comment]
@nikhilpsathyanathan did you figure out how it should work? It is not working for me. The link does not become ready.

**Comment by nikhilpsathyanathan** [comment]
It worked when i move it from the modal

**Comment by Ankush1613** [comment]
Hii it still an issue. Tried almost all of the available solutions nothing worked.
