### ISSUE TITLE
Exit flickers

### ISSUE THREAD

**Issue by dy** [plaid/react-plaid-link#293]
We're regularly having this with basic link setup:

https://user-images.githubusercontent.com/300067/213289415-f4cb01c4-b132-4d70-af26-fa2c4db5771f.mov
https://user-images.githubusercontent.com/300067/213289418-63cb0374-9ffe-4582-8887-0515e73c7e65.mov

**Comment by dy** [comment]
Ok, turns out that was 2 plaid iframes initialized same time, competing for focus.

**Comment by azuline** [comment]
We had the same issue, though the root cause was not two iframes. Another portal of ours had a FocusScope that competed with the Plaid iframe. Strangely enough, we only experienced this with the UK portal and not with the US portal.
