### ISSUE TITLE
Optionally allow sandbox attributes on Plaid iframe for added security?

### ISSUE THREAD

**Issue by mtomcal** [plaid/react-plaid-link#297]
Hi Plaid team,

My companies' security team asks that all iFrames to third-party sources include a [`sandbox`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox) attribute. In this case, I would do `sandbox="allow-scripts allow-popups"` to allow the Plaid iFrame to function. Would you be open to adding an optional API to allow this in Plaid Link and in the link-initialize script?

Thanks!

**Comment by phoenixy1** [comment]
Last month we added the sandbox attribute to the Link iframe -- I believe this should resolve your issue. Please re-open/re-file/comment here if it does not.
