### ISSUE TITLE
Remove plaid-link iframe when component is unmounted

### ISSUE THREAD

**Issue by JoshuaMorris** [plaid/react-plaid-link#30]
Every time the PlaidLink component is constructed, it creates a new iFrame in the DOM this is not removed when the component is unmounted.

**Comment by bpb27** [comment]
Doesn't look like the `exit` method is ever invoked: https://github.com/pbernasconi/react-plaid-link/blob/3db370ff9a2e2d9873e4fd758437980d47ecdb6e/src/PlaidLink.js#L144

**Comment by JoshuaMorris** [comment]
I believe I resolved this issue in the fork my company is using [CLCInc/react-plaid-link](
https://github.com/CLCInc/react-plaid-link)

**Comment by pbernasconi** [comment]
This should be fixed now in https://github.com/plaid/react-plaid-link/pull/81/

`v2.0.0` was just released, so please test it out by checking the updated `README` and let me know!

There's also a storybook to test using Hooks and the Component wrapper: 

https://plaid.github.io/react-plaid-link
