### ISSUE TITLE
Is there a way to skip the "Select your institution" page?

### ISSUE THREAD

**Issue by houseOfEorl** [plaid/react-plaid-link#306]
Is there a way to skip the "Select institution" page? I'm asking because I already know the institution that my client is using and don't want to ask it again.

![image](https://github.com/plaid/react-plaid-link/assets/7337085/c11a7632-f52c-45aa-bd4c-1c5bcb8c60ea)

I tried to pass the "routing_number" in the link token creation, but no luck.

![image](https://github.com/plaid/react-plaid-link/assets/7337085/4d34f632-47ac-48f8-8b1e-785cf0785229)

**Comment by phoenixy1** [comment]
Sorry for the delay in responding! For US/Canada, there is not. Using the Routing Number field like you're doing can help pre-select the institution, and you can also consider using the Returning User Experience (https://plaid.com/docs/link/returning-user/) as another way to pre-populate the institution, but it is not possible to skip the pane altogether

**Comment by maknz** [comment]
Just a gentle +1 that this is a real issue for many Plaid customers where we already know what institution the user is connecting to, and making them pick it twice sucks. This used to be a feature, and it was removed for some unknown reason.

It is good to hear the routing number can be used to help, but if I already have the `ins_` id, there is no reason we can't at least show only results for that ins on the institution select screen (or better yet, skip it entirely).

**Comment by rubendinho** [comment]
Moreover the routing number feature is very unreliable and often fails to highlight the bank, even if using Plaid's own supplied routing numbers.

**Comment by Hartistic** [comment]
Commenting because this shouldn't be closed and should be supported.  Please make this possible.

**Comment by hugo-advizr** [comment]
Same use case here, we already know the `institution_id` before opening link (we created our own screen to pick the institution with some extra options). Please let the institution screen to be skipped (or at least have it pre-selected) if an institution id is provided when creating the link token.

**Comment by hugo-advizr** [comment]
@phoenixy1 any plans to support this? thank you

**Comment by phoenixy1** [comment]
@hugo-advizr no, there are no current plans to add this beyond what is present via e.g. the [Returning User Experience](https://plaid.com/docs/link/returning-user/).

**Comment by scott-truthifi** [comment]
Would be great if you all could get this fixed - or offer some other alternative that accomplishes the same goal.  Your competitors offer this and it works really great for end users.  Thanks!

**Comment by vancodocton** [comment]
@phoenixy1 I research and figure out that Plaid had support this feature before, but now it is deprecated/onsoleted (by add `institution_id` in link token create api).

Can I ask for the reason why this feature was deprecated and there is no current plan for it?

**Comment by phoenixy1** [comment]
@vancodocton this was only ever supported in Europe (as the Modular Link feature). We've removed this functionality in Europe as improvements to Link have made it no longer necessary -- by the time this feature was discontinued, the vast majority of Modular Link customers had voluntarily migrated to other forms of Link for better ease of use and conversion.

**Comment by gogochickenleg** [comment]
It doesn’t have to skip the “Select institution” page, having a better highlight should be enough in my opinion. For example, only showing the pre-selected institution instead of a full list with it pinned at the top.

<img width="338" height="470" alt="Image" src="https://github.com/user-attachments/assets/5ca125b4-181b-41ba-862b-40f1b4361066" />
