### ISSUE TITLE
Plaid component refreshes my react application page

### ISSUE THREAD

**Issue by root365** [plaid/react-plaid-link#31]
Plaid component refreshes my react application page when clicked.  Please help me get through it.

**Comment by akinniyi** [comment]
@root365 Can you post your implementation here?

**Comment by pbernasconi** [comment]
This should be fixed now in https://github.com/plaid/react-plaid-link/pull/81/

`v2.0.0` was just released, so please test it out by checking the updated `README` and let me know!

There's also a storybook to test using Hooks and the Component wrapper: 

https://plaid.github.io/react-plaid-link
