### ISSUE TITLE
Whether reCAPTCHA can be replaced or skipped ?

### ISSUE THREAD

**Issue by MoMeakDong** [plaid/react-plaid-link#314]
![image](https://github.com/plaid/react-plaid-link/assets/43400338/8f37b92e-6723-45b4-ac93-2b44493a61c1)
 As shown in the figure, when I cannot access Google-related websites due to network restrictions, I will encounter this situation during the authentication process, which will cause the authentication process to get stuck. Is there any way to help me?
 Is there an api support to skip reCAPTCHA verification, or can I use other verification methods instead?

**Comment by phoenixy1** [comment]
The ReCAPTCHA verification prompt only appears in Link when Plaid detects a session as being particularly high risk. As a result, there is no way to skip ReCAPTCHA. Sorry. :-(
