### ISSUE TITLE
Can't use multiple <PlaidLink> on the same page

### ISSUE THREAD

**Issue by k-funk** [plaid/react-plaid-link#32]
I'm not sure why linkHandler is being attached to `window`(https://github.com/pbernasconi/react-plaid-link/blob/master/src/PlaidLink.js#L109), but if another <PlaidLink> component is on the page, it will override the previous linkHandler. Seems like you could just use `this.linkHandler = window.Plaid.create(...)`.

*Edit:* https://github.com/pbernasconi/react-plaid-link/pull/28 seems to fix this.

**Comment by pbernasconi** [comment]
This should be fixed now in https://github.com/plaid/react-plaid-link/pull/81/

`v2.0.0` was just released, so please test it out by checking the updated `README` and let me know!

There's also a storybook to test using Hooks and the Component wrapper: 

https://plaid.github.io/react-plaid-link
