### ISSUE TITLE
v3.5.0 missing dist folder

### ISSUE THREAD

**Issue by SavePointSam** [plaid/react-plaid-link#322]
v3.5.0 deployed today is missing the dist folder and causes my builds to fail.

**Comment by tzha-plaid** [comment]
@SavePointSam can you try with the latest version (3.5.1)? Does the latest version fix the issue?

**Comment by tzha-plaid** [comment]
I've been able to build successfully using version 3.5.1 locally, feel free to re-open if you're still facing issues!
