### ISSUE TITLE
Styling button

### ISSUE THREAD

**Issue by awguitar86** [plaid/react-plaid-link#33]
Is there any way to custom style the button that comes with this?

**Comment by lorensr** [comment]
`style` or `className` props:

https://github.com/pbernasconi/react-plaid-link/blob/master/src/PlaidLink.js#L156-L157

**Comment by pbernasconi** [comment]
This should be fixed now in https://github.com/plaid/react-plaid-link/pull/81/

`v2.0.0` was just released, so please test it out by checking the updated `README` and let me know!

There's also a storybook to test using Hooks and the Component wrapper: 

https://plaid.github.io/react-plaid-link
