### ISSUE TITLE
[Question]: vue-plaid-link or other bindings?

### ISSUE THREAD

**Issue by jclaessens97** [plaid/react-plaid-link#330]
Hi, I'm wondering if you ever plan to also have official supported libraries for frameworks other than react, like Vue in my case?

I found 2 unofficial community libraries but both are still on vue 2. I just ported `react-plaid-link` (just the LinkToken one, not the deprecated one) to Vue 3 for a side project of mine, so I can already provide you with a start if you want to, but I have no time whatsoever to maintain and update a vue 3 community fork.

Just wondering, since I already made a port :) 

Cheers!

**Comment by phoenixy1** [comment]
@jclaessens97 Thanks for asking! We don't currently have any plans to add additional supported libraries for other frameworks. If you'd like to provide a Vue3 repo for consideration as a third-party wrapper we could link to, that'd be great!

**Comment by jclaessens97** [comment]
Hi, @phoenixy1, finally found some time.

Please find it here: https://github.com/jclaessens97/vue-plaid-link
and as npm package: https://www.npmjs.com/package/@jcss/vue-plaid-link

Also note that oauth and web3 aren't implemented (yet), and only the non-deprecated flow is implemented.

**Comment by phoenixy1** [comment]
@jclaessens97 thanks for adding this! There's no need to add web3 support as that flow has been deprecated. However, at this time most user accounts are connected via OAuth flows, so we probably wouldn't link to this package until OAuth support has been added. Once you've got that in, let us know!

**Comment by jclaessens97** [comment]
Hi, I looked at it again and I already implemented the redirectUri. I just added extra examples for using composables and oauth so now it should be inline with `react-plaid-link` (apart from the deprecated `web3` and `public_token` flows ofcourse).

**Comment by jclaessens97** [comment]
@phoenixy1 I also added tests now so I think it should be ready :)

**Comment by phoenixy1** [comment]
@jclaessens97 excellent! I have a docs update PR in progress that adds this to our community libraries in the docs; I anticipate it will be published this week.

**Comment by jclaessens97** [comment]
@phoenixy1  Is there a way to follow the progress on your docs pr or is it on a private repo?

**Comment by phoenixy1** [comment]
@jclaessens97 it's in a private repo. I'll update here when it's published!

**Comment by phoenixy1** [comment]
Added to the docs: https://plaid.com/docs/api/libraries/#link-client-sdks

**Comment by jclaessens97** [comment]
Super! Thanks for the update.
