### ISSUE TITLE
Ready state is always false even though a proper link_token is created and passed.

### ISSUE THREAD

**Issue by SP26GreenTeam** [plaid/react-plaid-link#335]
I'm having issues with the ready state never turning true even though a proper link_token is getting passed to the link. I went through the https://github.com/plaid/react-plaid-link/issues/239 post and tried some of their solutions they proposed such as moving the "PlaidLinkButton" into a separate location from the token fetching, but the ready state is still never hitting true for some reason

Here is my linkbutton: https://github.com/SP26GreenTeam/BudgetGreen/blob/NewMain/Screens/PlaidLinkButton.tsx
and here is the "LoginPage": https://github.com/SP26GreenTeam/BudgetGreen/blob/NewMain/Screens/PlaidLoginScreen.tsx

Any suggestions would be appreciated!

**Comment by Ankush1613** [comment]
Hii, i'm facing this issue a lot. Please can uh tell me what solution you have applied to solve this issue ?
