### ISSUE TITLE
Plaid button

### ISSUE THREAD

**Issue by goblin280** [plaid/react-plaid-link#340]
Hey I dont really know how to code but I have been stuck on a Plaid bank button forever now and im just sick and tired of it not working. I need to verify my bank account on the etsy platform but when I go to click the "Connect your bank via plaid" **button** it literally just dosent do anything. I opened f12 and there are a couple issues in the console. If anybody could tell me what this is and how to make the button work that would be great. need up ASAP.
![image](https://github.com/plaid/react-plaid-link/assets/168210068/c7d4d4f4-a5d7-49f0-ac4f-3065b03c1269)

**Comment by phoenixy1** [comment]
This channel is for Plaid developers. If you are having trouble verifying your account on Etsy via Plaid, please contact Etsy support.
