### ISSUE TITLE
onEvent callback returns data with unknown `NUMBERS_SELECT_INSTITUTION` view_name

### ISSUE THREAD

**Issue by joshnies** [plaid/react-plaid-link#341]
The `onEvent` callback is returning an event with a `view_name` of `NUMBERS_SELECT_INSTITUTION`, which does not exist in Plaid's API. Occurs when trying to add a bank account.

**Comment by ToddKerpelman** [comment]
According to [the docs](https://plaid.com/docs/auth/coverage/same-day/#handling-link-events), you'll get this view name when a user goes through the `SAME_DAY_MICRODEPOSITS` flow with [Reroute to Credentials](https://plaid.com/docs/auth/coverage/same-day/#reroute-to-credentials)

**Comment by joshnies** [comment]
> According to [the docs](https://plaid.com/docs/auth/coverage/same-day/#handling-link-events), you'll get this view name when a user goes through the `SAME_DAY_MICRODEPOSITS` flow with [Reroute to Credentials](https://plaid.com/docs/auth/coverage/same-day/#reroute-to-credentials)

Roger that, this was pretty deep in the docs for something that I would assume to be listed in an API reference.

**Comment by phoenixy1** [comment]
Yeah, I would expect this to be in the SDK reference and it doesn't seem to be. I'll file a docs ticket.
