### ISSUE TITLE
linkTokenConfiguration.token:  is invalid, it must contain an environment name.

### ISSUE THREAD

**Issue by dfvalenciaviamericas** [plaid/react-plaid-link#342]
Hi Plaid 

i am trying to run tiny TinyQuickstartReactNative using this variables in the .env file
PLAID_CLIENT_ID=*********our_plaid_client_id**************
PLAID_SECRET=*******our_plaid_secret*********
PLAID_ENV=DEV
PLAID_SANDBOX_REDIRECT_URI=https://cdn-testing.plaid.com/link/v2/stable/sandbox-oauth-a2a-react-native-redirect.html
PLAID_ANDROID_PACKAGE_NAME=com.tinyquickstartreactnative

however when i click in the "open link button" i am receiving this message error : 
 {"error": {"displayMessage": "linkTokenConfiguration.token:  is invalid, it must contain an environment name.", "errorCode": "6", "errorDisplayMessage": "linkTokenConfiguration.token:  is invalid, it must contain an environment name.", "errorJson": null, "errorMessage": "linkTokenConfiguration.token:  is invalid, it must contain an environment name.", "errorType": "creation error", "metadata": {"institution": null, "linkSessionId": null, "metadataJson": null, "requestId": null, "status": null}}}

<img width="352" alt="image" src="https://github.com/plaid/react-plaid-link/assets/162498989/a6337ffc-2e40-4cb5-9241-e50ac0da303b">

**Comment by phoenixy1** [comment]
It sounds like the app's backend call to `/link/token/create` might have failed -- can you verify that you successfully created a link token? You should be able to check your logs at https://dashboard.plaid.com/developers/logs. If the call failed, an error code for the failure should be in the logs.

**Comment by dfvalenciaviamericas** [comment]
I view on the logs but not see any call there. Also here you can see my server.js file where i am setting my env variables. It seems that is not taking thos env

/*
server.js – Configures the Plaid client and uses Express to defines routes that call Plaid endpoints in the Sandbox environment. Utilizes the official Plaid node.js client library to make calls to the Plaid API.
*/

import dotenv from 'dotenv';
require('dotenv').config();
import express from 'express';
import {urlencoded, json} from 'body-parser';
import session from 'express-session';
import {Configuration, PlaidApi, PlaidEnvironments} from 'plaid';
import {
  PLAID_ENV,
  PLAID_CLIENT_ID,
  PLAID_SECRET,
  PLAID_ANDROID_PACKAGE_NAME,
  PLAID_SANDBOX_REDIRECT_URI,
} from 'react-native-dotenv';

dotenv.config();
const {
  PLAID_ENV,
  PLAID_CLIENT_ID,
  PLAID_SECRET,
  PLAID_ANDROID_PACKAGE_NAME,
  PLAID_SANDBOX_REDIRECT_URI,
} = process.env;
const app = express();
const port = 8080;
console.log(PLAID_ENV);
app.use(
  // FOR DEMO PURPOSES ONLY
  // Use an actual secret key in production
  session({secret: 'bosco', saveUninitialized: true, resave: true}),
);

app.use(urlencoded({extended: false}));
app.use(json());

// Configuration for the Plaid client
const config = new Configuration({
  basePath: PlaidEnvironments[PLAID_ENV],
  baseOptions: {
    headers: {
      'PLAID-CLIENT-ID': PLAID_CLIENT_ID,
      'PLAID-SECRET': PLAID_SECRET,
      'Plaid-Version': '2020-09-14',
    },
  },
});

//Instantiate the Plaid client with the configuration
const client = new PlaidApi(config);

//Creates a Link token and return it
app.post('/api/create_link_token', async (req, res, next) => {
  let payload = {};
  //Payload if running iOS
  if (req.body.address === 'localhost') {
    console.log(PLAID_ENV);
    payload = {
      user: {client_user_id: req.sessionID},
      client_name: 'Plaid Tiny Quickstart - React Native',
      language: 'en',
      products: ['auth'],
      country_codes: ['US'],
      redirect_uri: PLAID_SANDBOX_REDIRECT_URI,
    };
  } else {
    console.log(PLAID_ENV);
    //Payload if running Android
    payload = {
      user: {client_user_id: req.sessionID},
      client_name: 'Plaid Tiny Quickstart - React Native',
      language: 'en',
      products: ['auth'],
      country_codes: ['US'],
      android_package_name: PLAID_ANDROID_PACKAGE_NAME,
    };
  }
  const tokenResponse = await client.linkTokenCreate(payload);
  res.json(tokenResponse.data);
});

// Exchanges the public token from Plaid Link for an access token
app.post('/api/exchange_public_token', async (req, res, next) => {
  const exchangeResponse = await client.itemPublicTokenExchange({
    public_token: req.body.public_token,
  });

  // FOR DEMO PURPOSES ONLY
  // Store access_token in DB instead of session storage
  req.session.access_token = exchangeResponse.data.access_token;
  res.json(true);
});

// Fetches balance data using the Node client library for Plaid
app.post('/api/balance', async (req, res, next) => {
  const access_token = req.session.access_token;
  const balanceResponse = await client.accountsBalanceGet({access_token});
  res.json({
    Balance: balanceResponse.data,
  });
});

app.listen(port, () => {
  console.log(`Backend server is running on port ${port}...`);
  console.log(PLAID_ENV);
});

**Comment by dfvalenciaviamericas** [comment]
I am getting this error when trying to call create_link_token

<img width="634" alt="image" src="https://github.com/plaid/react-plaid-link/assets/162498989/458f83de-cefa-4547-92d7-6f0a19c1f72c">


error catch create_link_token
 LOG  [SyntaxError: JSON Parse error: Unexpected character: <]

**Comment by RevanthGundala** [comment]
Running into the same issue

**Comment by amloelxer** [comment]
@dfvalenciaviamericas @RevanthGundala did you ever figure this out??

**Comment by phoenixy1** [comment]
Also, make sure the .env.example file is renamed to .env.

I'm going to close this out since it's a bit old -- if anyone else is seeing the same issue, please re-open a new issue.

**Comment by dipankarkarmakar** [comment]
same issue, I tried in update mode to create a link token
