### ISSUE TITLE
TypeError: React.createClass is not a function

### ISSUE THREAD

**Issue by lakshmisanthi** [plaid/react-plaid-link#36]
I am using react-plaid-link, Now i am upgrade my react-js version from 15.6.1 to 16.4.1.
From that, I am getting following issue. 
I know this is version problem, But i want latest version of react-js. So any one can help to resolve it.

**TypeError: React.createClass is not a function**

`Object../node_modules/react-plaid-link/dist/PlaidLink.js
node_modules/react-plaid-link/dist/PlaidLink.js:7
   4 | var PropTypes = require('prop-types');
   5 | var ReactScriptLoaderMixin = require('react-script-loader').ReactScriptLoaderMixin;
   6 | 
>  7 | var PlaidLink = React.createClass({
   8 |   displayName: 'PlaidLink',
   9 | 
  10 |   mixins: [ReactScriptLoaderMixin],
View compiled
__webpack_require__
/home/santhi/Documents/mvp_testing/webpack/bootstrap 46193b11a979a174f68b:659
  656 | };
  657 | 
  658 | // Execute the module function
> 659 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  660 | 
  661 | // Flag the module as loaded
  662 | module.l = true;`

**Comment by pbernasconi** [comment]
This should be fixed now in https://github.com/plaid/react-plaid-link/pull/81/

`v2.0.0` was just released, so please test it out by checking the updated `README` and let me know!

There's also a storybook to test using Hooks and the Component wrapper: 

https://plaid.github.io/react-plaid-link
