### ISSUE TITLE
Delay PlaidLink initialization

### ISSUE THREAD

**Issue by midnightcodr** [plaid/react-plaid-link#37]
I am building a mobile webapp which allows user to select their bank from a list of banks (with `institution` set in each `PlaidLink` component. The current behavior of PlaidLink is once it's rendered, a number of initialization will occur, which makes the performance of the loading quite slow. I am wondering if there is a way to postpone the init steps, that is, making calls to Plaid servers only when a button is clicked.

**Comment by pbernasconi** [comment]
This should be fixed now in https://github.com/plaid/react-plaid-link/pull/81/

`v2.0.0` was just released, so please test it out by checking the updated `README` and let me know!

There's also a storybook to test using Hooks and the Component wrapper: 

https://plaid.github.io/react-plaid-link
