### ISSUE TITLE
Should be able to pass a disabled prop to override the component state

### ISSUE THREAD

**Issue by bsiddiqui** [plaid/react-plaid-link#44]

**Comment by ryan28561** [comment]
I found a way to disable it by adding an onClick and throwing an error in the onClick. Otherwise it calls the onClick and then opens it anyway. You can also override the css by passing prop style={{}} and you can add your own class name to make it at least look disabled.

**Comment by pbernasconi** [comment]
This should be fixed now in https://github.com/plaid/react-plaid-link/pull/81/

`v2.0.0` was just released, so please test it out by checking the updated `README` and let me know!

There's also a storybook to test using Hooks and the Component wrapper: 

https://plaid.github.io/react-plaid-link
