### ISSUE TITLE
CORS issue 

### ISSUE THREAD

**Issue by svvedam** [plaid/react-plaid-link#45]

**Comment by svvedam** [comment]
When I click on continue button after logging in I am seeing the error "Uncaught TypeError: _components_util_EBPACK_IMPORTED_MODULE_7__.default.makeRequest is not a function at Object.handleOnSuccess[as onSuccess] App.js.7
at Object.connected(link-initialize.js:1)
at link-initialize.js:1

GET https://cdn.plaid.com/link/v2/stable/link-initialize.js.map 403 (Forbidden
![Screen Shot 2019-04-06 at 2 10 13 PM](https://user-images.githubusercontent.com/47256735/55673721-93795400-5879-11e9-9b50-993cb4770c46.png)
![Screen Shot 2019-04-06 at 2 11 54 PM](https://user-images.githubusercontent.com/47256735/55673722-93795400-5879-11e9-93e7-2b73a8973316.png)

)

**Comment by svvedam** [comment]
Thank you for uploading the code for the Plaid link. I am working on a budget app for my learning purpose. Please help me with this issue. I am not sure what I am missing.

**Comment by cancan101** [comment]
Similar to #47.

**Comment by pbernasconi** [comment]
Hey @svvedam @cancan101 – Sorry that I have been unresponsive for this repo.

In the next few weeks, I'm planning to move this repo over to the official [Plaid](https://github.com/plaid/) organization, and will be addressing this, and the other open issues then!

Stay tuned for an update soon.

**Comment by icruzr93** [comment]
Hi @pbernasconi, any news about these errors?

**Comment by swrobel** [comment]
@pbernasconi any update?

**Comment by pbernasconi** [comment]
This should be fixed now in https://github.com/plaid/react-plaid-link/pull/81/

`v2.0.0` was just released, so please test it out by checking the updated `README` and let me know!

There's also a storybook to test using Hooks and the Component wrapper: 

https://plaid.github.io/react-plaid-link
