### ISSUE TITLE
Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by cancan101** [plaid/react-plaid-link#46]
```
index.js:1437 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in PlaidLink
```
```
handleLinkOnLoad | @ | PlaidLink.js:127
```
which is this code: https://github.com/pbernasconi/react-plaid-link/blob/e1926387784c9d92b6d59ff63e5f260de62cf7c0/src/PlaidLink.js#L144

**Comment by ttezel** [comment]
+1 on this

**Comment by pbernasconi** [comment]
Hey @svvedam @cancan101 – Sorry that I have been unresponsive for this repo.

In the next few weeks, I'm planning to move this repo over to the official [Plaid](https://github.com/plaid/) organization, and will be addressing this, and the other open issues then!

Stay tuned for an update soon.

**Comment by erikchristianson** [comment]
@pbernasconi  Any updates on this?

**Comment by Joycechocho** [comment]
+1 Same here

**Comment by goleary** [comment]
@pbernasconi is anyone working on this repo? seems pretty dead.  There are plenty of people willing to help but no one is even looking at the PRs...

**Comment by pbernasconi** [comment]
This should be fixed now in https://github.com/plaid/react-plaid-link/pull/81/

`v2.0.0` was just released, so please test it out by checking the updated `README` and let me know!

There's also a storybook to test using Hooks and the Component wrapper: 

https://plaid.github.io/react-plaid-link
