### ISSUE TITLE
Cross-Origin Read Blocking (CORB) blocked cross-origin response

### ISSUE THREAD

**Issue by cancan101** [plaid/react-plaid-link#47]
I am seeing:
`Cross-Origin Read Blocking (CORB) blocked cross-origin response https://sandbox.plaid.com/link/client/get with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.`

![image](https://user-images.githubusercontent.com/51059/56942048-57d35200-6ae6-11e9-915b-b252e1ad8c34.png)

**Comment by pbernasconi** [comment]
Sorry that I have been unresponsive for this repo.

In the next few weeks, I'm planning to move this repo over to the official Plaid organization, and will be addressing this, and the other open issues then!

Stay tuned for an update soon.

**Comment by EP36** [comment]
Any update on this? Having similar issue myself

**Comment by anthonywebb** [comment]
I am seeing the same, can anyone help?

**Comment by anthonywebb** [comment]
Looking closer at the error and the error was actually thrown because I was passing a null token.  Giving it an actual token did the trick
