### ISSUE TITLE
give button type="button"

### ISSUE THREAD

**Issue by Plummat** [plaid/react-plaid-link#48]
right now, without it, initializing this inside a form will trigger the Plaid Modal when hitting enter to submit said form. Should be a straightforward fix.

**Comment by mclapa** [comment]
Indeed this is causing problems when nested inside other forms, perhaps a default type="button" unless other props passed in?

**Comment by ricardasjak** [comment]
I have same problem.
I would love to use plaid hook instead as per https://github.com/plaid/react-plaid-link/pull/63

**Comment by ricardasjak** [comment]
Here is my solution to this problem. I create my own PlaidButton component, where inside I have:
`   
 const plaidRef = useRef<HTMLDivElement>(null);
    useEffect(() => {
        const clickHandler = (e) => {
            e.preventDefault();
        };
        plaidRef.current.addEventListener('click', clickHandler);
        return () => plaidRef.current.removeEventListener('click', clickHandler);
    }, [plaidRef]);

    return (
        <div ref={plaidRef}>
            <PlaidLink  {...plaidOptions} className='my-fancy-button' style={{}}>
                Add bank account
            </PlaidLink>
        </div>
    );

**Comment by pbernasconi** [comment]
Fixed in https://github.com/plaid/react-plaid-link/pull/83

**Comment by pbernasconi** [comment]
@ricardasjak - Hooks are now available! (https://github.com/plaid/react-plaid-link/pull/81)

`v2.0.0` was just released, so please test it out by checking the updated `README` and let me know!

There's also a storybook to test using Hooks and the Component wrapper: 

https://plaid.github.io/react-plaid-link
