### ISSUE TITLE
Replace Wrapper div with <>

### ISSUE THREAD

**Issue by craig1123** [plaid/react-plaid-link#49]
The extra div is really messing up my styles. Can we replace that with a `<>` or `<React.Fragment>`?

**Comment by pbernasconi** [comment]
This should be fixed now in https://github.com/plaid/react-plaid-link/pull/81/

`v2.0.0` was just released, so please test it out by checking the updated `README` and let me know!

There's also a storybook to test using Hooks and the Component wrapper: 

https://plaid.github.io/react-plaid-link
