### ISSUE TITLE
Cannot find module 'react-plaid-link'

### ISSUE THREAD

**Issue by jtdaugh** [plaid/react-plaid-link#57]
I'm seeing this error newly within the past 24 hours, in a docker app that has react-plaid-link as a dependency. Changing my package.json to restrict the dep to v1.2.0 fixed the issue. It seems potentially related to commit f48fed5dd0ac4ecae403325edb30c895d53295ab

Error: Cannot find module 'react-plaid-link'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/dist/server.bundle.js:3998:18)

**Comment by dinodevrpn** [comment]
getting same issue, let me know if you have resolved it, i am using node -v 8

**Comment by travmichwill** [comment]
v1.3.1 is working for me, v1.4.0 and greater are not working.
Node v10.16.1
NPM 6.9.0

**Comment by pbernasconi** [comment]
Thanks for raising this – I've just released v1.5.0 that re-exposes the main as `lib/index.js`
