### ISSUE TITLE
Warning when used with create react app

### ISSUE THREAD

**Issue by mikecousins** [plaid/react-plaid-link#58]
When installing packages we get a warning in this package:

>warning "react-plaid-link > react-load-script@0.0.6" has unmet peer dependency "prop-types@>=15".

**Comment by pbernasconi** [comment]
`v2.0.0` was just released, so please test it out by checking the updated `README` and let me know!

There's also a storybook to test using Hooks and the Component wrapper: 

https://plaid.github.io/react-plaid-link
