### ISSUE TITLE
There is neither CHANGELOG.md nor Release Descriptions

### ISSUE THREAD

**Issue by wheeler** [plaid/react-plaid-link#59]
As a user of this package it is very difficult to tell what changes between versions so very hard to know if upgrading versions is safe, if there are new features that can be used, or if there are useful fixes. Please add some description of releases. Thanks!

**Comment by jung35** [comment]
Yeah, the `institution` was removed 2 releases ago and that threw things off on application im working on. the readme isnt up to date because of that. changelog would be very helpful

**Comment by sharan-wednesday** [comment]
@jung35 is it still possible to use institution on any release version of the library?

My use case is to preselect the institution

**Comment by pbernasconi** [comment]
Added today (https://github.com/plaid/react-plaid-link/pull/81/)

`v2.0.0` was just released, so please test it out by checking the updated `README` and let me know!

There's also a storybook to test using Hooks and the Component wrapper: 

https://plaid.github.io/react-plaid-link

**Comment by wheeler** [comment]
@pbernasconi Glad to see the improvement!

It would be nice to add in the pre-2.0.0 versions in the CHANGELOG. Many users may be upgrading from some lower 1.x version and not know about 1.x intermediate changes that may impact them.
