### ISSUE TITLE
Expose the onClick function to Support Custom Buttons

### ISSUE THREAD

**Issue by CameronJ26** [plaid/react-plaid-link#60]
Styling the button is unnecessarily complicated if you are not using standard CSS rules, for example we use styled components and already have a styled button, but it's not possible to use it instead of the build in Plaid button.

Also, there's no way to add extra tags to the button, such as tags for accessibility.

It is possible to do this, but it results in a nested button, which again is bad for accessibility:
```
<PlaidLink
  ...
>
  <StyledButton>Testing</StyledButton>
</PlaidLink>
```

It'd be great if a function was exposed that would allow disabling the built in button and using the custom one instead. Something like:

```
import {PlaidLink, startPlaid} from 'react-plaid-link';
<PlaidLink
  buttonDisabled={true}
>
  <StyledButton onClick={() => startPlaid()}>Testing</StyledButton>
</PlaidLink>
```

@pbernasconi

**Comment by pbernasconi** [comment]
This should be fixed now in https://github.com/plaid/react-plaid-link/pull/81/

`v2.0.0` was just released, so please test it out by checking the updated `README` and let me know!

There's also a storybook to test using Hooks and the Component wrapper: 

https://plaid.github.io/react-plaid-link
