### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow'.

### ISSUE THREAD

**Issue by VasiliSolodar** [plaid/react-plaid-link#61]
Looks like that there is some infrastructure changes on Plaid's side that lead to unexpected behavior in plaid-link. We're using plaid's postMessages to handle all authorization cases. But when user selects bank that requires OAuth authorization type and completes necessary steps (or not), Plaid doesn't send postMessage about that.
Steps to reproduce:
- set plaid env to "sandbox"
- start auth flow in plaid
- Select bank that requires OAuth in banks search page (i've used almost all UK banks (HSBC (UK), Barclays))
- on bank's OAuth page(which is Plaid's mocked page since we're on sandbox) press any button "Grant access", "Simulate Error" ect.
- look into browser console
![postMessage](https://user-images.githubusercontent.com/50202057/66258509-ab8d4a00-e7ae-11e9-8707-f87de89d868d.jpg)

Not sure if it affects "development" and "production" env.

**Comment by rublev** [comment]
+1

**Comment by nicolasfeoli** [comment]
+2

**Comment by pbernasconi** [comment]
`v2.0.0` was just released, so please test it out by checking the updated `README` and let me know!

There's also a storybook to test using Hooks and the Component wrapper: 

https://plaid.github.io/react-plaid-link

**Comment by skylarmb** [comment]
closed as I dont think this is an issue anymore
