### ISSUE TITLE
options.webhook must be a non-empty string URL

### ISSUE THREAD

**Issue by xanderflood** [plaid/react-plaid-link#62]
I'm using this (templated) command in my javascript:

```
    var handler = Plaid.create({
      clientName: 'Plaid Quickstart',
      env: '{{ .plaid_environment }}',
      product: products,
      key: '{{ .plaid_public_key }}',
      webhook: '{{ .plaid_webhook_url }}',
      onSuccess: function(public_token) {
        authenticatedRequest(
          'POST',
          '/api/v1/add_plaid_item',
          { "public_token": public_token },
          function(data) {
            $('#intro').hide();
            refreshAccountTable();
            $('#app, #steps').fadeIn('slow');
          }
        )
      },
      onExit: function(err, metadata) {
        // The user exited the Link flow.
        if (err != null) {
          // The user encountered a Plaid API error prior to exiting.
          console.log(err, '{{ .plaid_webhook_url }}');
        }
        // metadata contains information about the institution
        // that the user selected and the most recent API request IDs.
        // Storing this information can be helpful for support.
      },
    });

    $('#link-btn').on('click', function(e) {
      handler.open();
    });
```

I can confirm that `webhook` is being set to `/api/v1/webhook` as I want. But when I go through the login flow, it ends with a 400 response from https://sandbox.plaid.com/link/item/create with this body:
```
{
  "display_message": null,
  "error_code": "INVALID_FIELD",
  "error_message": "options.webhook must be a non-empty string URL",
  "error_type": "INVALID_REQUEST",
  "request_id": "...",
  "suggested_action": null
}
```

When I check the response body, I see the following underneath the top level:
<img width="257" alt="Screen Shot 2019-10-09 at 10 07 06 PM" src="https://user-images.githubusercontent.com/6438707/66533537-46549400-eae1-11e9-930d-5638618e917f.png">
so the field appears to be set.

**Comment by pbernasconi** [comment]
This should be fixed now in https://github.com/plaid/react-plaid-link/pull/81/

`v2.0.0` was just released, so please test it out by checking the updated `README` and let me know!

There's also a storybook to test using Hooks and the Component wrapper: 

https://plaid.github.io/react-plaid-link
