### ISSUE TITLE
React Native – Plans to support iOS dark mode?

### ISSUE THREAD

**Issue by dustinhorton** [plaid/react-plaid-link#64]
I'd of posted this in [https://github.com/plaid/plaid-link-examples](https://github.com/plaid/plaid-link-examples), or even [https://github.com/plaid/link](https://github.com/plaid/link), but neither of the repos appear to support issues?

![Image from iOS](https://user-images.githubusercontent.com/378165/67231658-f50ba500-f3fc-11e9-863b-46118532660b.png)

See the screenshot—illegible.

**Comment by pbernasconi** [comment]
Hi please re-open this issue in https://github.com/plaid/react-native-plaid-link-sdk/!
