### ISSUE TITLE
button element should have "type='button'" on it

### ISSUE THREAD

**Issue by jeffbarg** [plaid/react-plaid-link#67]
When I embed the PlaidLink in a form, it will automatically submit the form since it does not explicitly set type="button" instead of submit.

**Comment by HugoGiraudel** [comment]
This is a duplicate of #48.

**Comment by pbernasconi** [comment]
Fixed in https://github.com/plaid/react-plaid-link/pull/83

**Comment by jeffbarg** [comment]
Thanks a lot! Really appreciate this :)
