### ISSUE TITLE
Extract account balance data from http call

### ISSUE THREAD

**Issue by YeeWong11** [plaid/react-plaid-link#68]
When inspecting the network traffic during the Plaid link widget flow, I can see that we are getting account balances when calling `https://sandbox.plaid.com/link/item/create`. But none of the onXXXXX callbacks are getting this in their payload. Is there a way to retrieve this data from the client side?  

```
Request URL: https://sandbox.plaid.com/link/item/create
Request Method: POST
Status Code: 200 OK
```

Payload in network inspection
```
{
  "accounts": [
    {
      "account_id": "4WLLyEd7ZrukbWNrkJfefe3FEgrFREGREGERG",
      "balances": {
        "available": 100,
        "currency": "USD",
        "current": 110,
        "localized": {
          "available": "$100.00",
          "current": "$110.00"
        }
      },
      "mask": "0000",
      "name": "Plaid Checking",
      "subtype": "checking",
      "type": "depository"
    },
    {
      "account_id": "NZKKa4yzPuoU8hHJBIHHHhhhNaFWDXjaz",
      "balances": {
        "available": 200,
        "currency": "USD",
        "current": 210,
        "localized": {
          "available": "$200.00",
          "current": "$210.00"
        }
      },
      "mask": "1111",
      "name": "Plaid Saving",
      "subtype": "savings",
      "type": "depository"
    },
    {
      "account_id": "P1zzNPAokeogpkreogkrefkwLkGmaF7MXkjb",
      "balances": {
        "available": null,
        "currency": "USD",
        "current": 1000,
        "localized": {
          "available": null,
          "current": "$1,000.00"
        }
      },
```

**Comment by pbernasconi** [comment]
This is available in the `metadata` object returned via the `onSuccess(token, metadata)` callback – should be available in v2.0.0

**Comment by cthomaschase** [comment]
@pbernasconi to clarify, the `balances` collection is now returned in the `metadata` object returned on the success callback when using use `usePlaidLink` hook? That's great and would save a roundtrip to query initial balances.

I'm not seeing it with in v2.0.1 though, am I missing something?

**Comment by pbernasconi** [comment]
Ah apologies @cthomaschase – it seems `balances` are not returned in the `onSuccess` callback per our docs: https://plaid.com/docs/#onsuccess-metadata-schema

<img width="634" alt="Screen Shot 2020-03-19 at 6 09 07 AM" src="https://user-images.githubusercontent.com/1716394/77037029-461dc600-69a8-11ea-9d2d-8e4eb7345290.png">

I would recommend opening a Support request in our dashboard to ask for this feature to be returned – however if I recall correctly, we don't want to expose PII and sensitive data client-side, and instead recommend using `/accounts/get` or `/balance/get` endpoints to pull balance data
