### ISSUE TITLE
During bank connectivity in Android landscape view, the bank user name field enters text backwards.

### ISSUE THREAD

**Issue by justinAurand** [plaid/react-plaid-link#69]
This issue occurs for Android users in landscape (not portrait) mode.

When a user attempts to connect a bank using their bank credentials, the characters entered into the user name field are entered in reverse order. This image displays the user experience when the user enters "user_good" as their user name:

![UI](https://user-images.githubusercontent.com/1655704/72543054-2573ab80-3853-11ea-8c02-e84c5f8c4002.png)

The following is the OS and build information of the device used to recreate this defect:

![OSandBuild](https://user-images.githubusercontent.com/1655704/72543371-9ca93f80-3853-11ea-9349-5b4530288b9f.png)

Thanks!

**Comment by davidzhanghp** [comment]
hi @justinAurand 

Thank you for bringing this issue to our attention. Our team is aware of this issue. They have put it on their internal backlog and will address it eventually.

Thanks!
