### ISSUE TITLE
Doesn't work with yarn v2, missing peer dependency for prop-types

### ISSUE THREAD

**Issue by mikecousins** [plaid/react-plaid-link#74]
We need to add prop-types to the peerDependencies

https://github.com/yarnpkg/berry/issues/913

**Comment by mikecousins** [comment]
This will probably fix #58 as well.

**Comment by pbernasconi** [comment]
This should be fixed now in https://github.com/plaid/react-plaid-link/pull/81/

Please re-open this issue if it's not!
