### ISSUE TITLE
Plaid opens in tiny window at the top of the page

### ISSUE THREAD

**Issue by jmitchell33** [plaid/react-plaid-link#78]
I'm having an issue here Plaid is opening in a tiny section on the top of the page - and I'm running short on ideas of how to address this since all of the code is coming from Plaid when it appends to the body.  The image should explain everything...  Is there a way I can create a div or modal for this to live in, instead of plaid appending to the body?

![Screenshot from 2020-03-05 13-59-58](https://user-images.githubusercontent.com/2698727/76019813-53d74400-5ef0-11ea-982e-00be2a8e9f19.png)

**Comment by JPWallhorn** [comment]
Are you using `z-index` in your application? Something that would overlay the popup?

**Comment by anthonywebb** [comment]
@jmitchell33 did you figure this out?  Mine is loading the exact same,  curious what css you had to fiddle with to get it to work?

**Comment by jmitchell33** [comment]
Yes - how I'm getting around it is by setting invalid values for the
following CSS, which lets the class I have for iframes handle it properly.


const style = {
breakStyle : {
padding: 'breakThisField',
outline: 'breakThisField',
background: 'breakThisField',
border: 'breakThisField',
borderRadius: 'breakThisField'
}
}

return (
<PlaidLink
...
style={style.breakStyle}
>
{props.button_text}
</PlaidLink>
);
