### ISSUE TITLE
linkCustomizationName prop on 'react-plaid-link'

### ISSUE THREAD

**Issue by artonmirakaj** [plaid/react-plaid-link#80]
unable to pass in linkCustomizationName prop into <PlaidLink /> to get customized plaid link

import PlaidLink from 'react-plaid-link';

<PlaidLink
clientName="plaid"
env="sandbox"
publicKey="ADD_PUBLIC_KEY_HERE"
product={['assets']}
onSuccess={this.handleOnSuccess}
linkCustomizationName="my_customized_plaid"
>
Connect bank account
</PlaidLink>

this prop does not exist in 'react-plaid-link'

is there another way around this or do i have to wait for a new version of 'react-plaid-link' to have that prop?

- please email me at artonm26@gmail.com

**Comment by pbernasconi** [comment]
#81 should solve this for you shortly!
