### ISSUE TITLE
PlaidLink propTypes Issue

### ISSUE THREAD

**Issue by athielen2** [plaid/react-plaid-link#84]
**Version: 2.0.1**

When using the PlaidLink component, I get the following error if `key` is not specified as a prop to `PlaidLink`:

`Property 'key' is missing in type '{ children: string; clientName: string; env: string; product: string[]; publicKey: string; onSuccess: () => void; }' but required in type 'Pick<InferProps<{ className: Validator<string>; clientName: Validator<string>; env: Validator<string>; key: Validator<string>; product: Validator<(string | null | undefined)[]>; onSuccess: Validator<(...args: any[]) => any>; ... 9 more ...; children: Requireable<...>; }>, "key">'.`

This appears to be cause by key being specified as a required propType in the PlaidLink definition. Is that that is supposed to be `publicKey` instead of `key`?

`declare const PlaidLink: {
    (props: PlaidLinkPropTypes): JSX.Element;
    displayName: string;
    propTypes: {
        className: PropTypes.Validator<string>;
        clientName: PropTypes.Validator<string>;
        env: PropTypes.Validator<string>;
        key: PropTypes.Validator<string>;
        product: PropTypes.Validator<(string | null | undefined)[]>;
        onSuccess: PropTypes.Validator<(...args: any[]) => any>;
        countryCodes: PropTypes.Requireable<any[]>;
        language: PropTypes.Requireable<string>;
        onEvent: PropTypes.Requireable<(...args: any[]) => any>;
        onExit: PropTypes.Requireable<(...args: any[]) => any>;
        onLoad: PropTypes.Requireable<(...args: any[]) => any>;
        token: PropTypes.Requireable<string>;
        userEmailAddress: PropTypes.Requireable<string>;
        userLegalName: PropTypes.Requireable<string>;
        webhook: PropTypes.Requireable<string>;
        children: PropTypes.Requireable<PropTypes.ReactElementLike>;
    };
};`

Let me know if you need more information.

**Comment by jgonera** [comment]
Same issue. It seems the TypeScript type is correct and the props are not.
