### ISSUE TITLE
Callback types are not specific

### ISSUE THREAD

**Issue by jgonera** [plaid/react-plaid-link#85]
Previously external types were more complete:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-plaid-link/index.d.ts#L66-L84

Now we have just this:
https://github.com/plaid/react-plaid-link/blob/fc3913d918a6ddd1f256c5559c0abe7f73cccdae/src/types/index.ts#L16

This forces me to declare types for my callbacks manually in my code. Could we add previous callback types to the TS rewrite?

**Comment by jgonera** [comment]
Similarly, `product` types were more specific:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-plaid-link/index.d.ts#L30-L41

vs:
https://github.com/plaid/react-plaid-link/blob/fc3913d918a6ddd1f256c5559c0abe7f73cccdae/src/types/index.ts#L13

**Comment by jekh** [comment]
It would indeed be hugely beneficial to include types for these functions, either as part of this package or by importing types from elsewhere, for example https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/plaid-link/index.d.ts#L40

**Comment by skylarmb** [comment]
hey @jekh @jgonera im working on this here https://github.com/plaid/react-plaid-link/tree/sb-improve-examples-and-types

**Comment by skylarmb** [comment]
Hi all please check out the the new types that are now provided by the package. They should meet your needs:

https://github.com/plaid/react-plaid-link/blob/master/src/types/index.ts#L24-L83

https://github.com/plaid/react-plaid-link/blob/master/examples/hooks.tsx#L26-L40
