### ISSUE TITLE
Not entering Update mode after setting token prop state

### ISSUE THREAD

**Issue by cthomaschase** [plaid/react-plaid-link#92]
Is anyone else still having this issue? 

I'm using v2.0.2 `usePlaidLink` hook. When setting the token prop using state, the linker is not opening in `update` mode.

**Comment by skatea09** [comment]
I am experiencing this issue as well on v2.0.3

**Comment by sdzharkov** [comment]
This is currently a problem for myself as well on v2.0.3.

**Comment by atomkirk** [comment]
looks like theres a fix for it https://github.com/plaid/react-plaid-link/commit/c5002e68572dc4d3d1f2921f2520a00bb155568c

3 days ago, wish they'd publish :)

**Comment by atomkirk** [comment]
if you're in a hurry ya'll can use my fix until they get it fixed

```
"react-plaid-link": "git://github.com/atomkirk/react-plaid-link.git#7fa8508e5224c3b56520e496d48d510a6450af4a"
```

**Comment by pbernasconi** [comment]
Hey all - just published 2.1.0 with an updated `token` initialization. Hope this fixes your issue via #95!

**Comment by atomkirk** [comment]
still getting this
![image](https://user-images.githubusercontent.com/2091439/77973587-dc5bc100-72b1-11ea-9a25-4339e4e0933a.png)

**Comment by cthomaschase** [comment]
Thanks @pbernasconi for pushing the fix. Looks like I'm getting the same error now as @atomkirk when using v2.1.0

**Comment by otherchen** [comment]
Hey @cthomaschase, @atomkirk, @sdzharkov I tried recreating the error locally and I'm unable to reproduce. Do you mind sending over steps on how I can reproduce?

For what it's worth, I'm testing it using storybook and I am able to update the token successfully: https://github.com/plaid/react-plaid-link/compare/ac-reproduce-destroy-error

You can test my example above by:
1. cloning the repo
2. checking out the `ac-reproduce-destroy-error` branch
3. running `make setup`
4. running `make watch`
5. going to `http://localhost:6006/?path=/story/react-plaid-link--hooks`
6. generate a public_token through curling `development.plaid.com/item/public_token/create`
7. passing it into the LINK_TOKEN field in storybook
8. and clicking the `Use new Link Token` button

At this point, Link should open correctly

**Comment by cthomaschase** [comment]
Still a WIP, but it looks to occur when I reset the `token` state to `null` from the onSuccess callback, after successfully updating an item. I'm yet to reproduce in your branch when I do the same.

Stay tuned...

**Comment by otherchen** [comment]
Sounds good @cthomaschase! It'd be great if there's an example you could recreate with storybook so I can reproduce on my end.

**Comment by cthomaschase** [comment]
@otherchen circling back on this one. After converting to TS I'm no longer seeing the derivative issue referenced above by @atomkirk. Wish I had more definitive answer. All seems good as this point.

https://github.com/plaid/react-plaid-link/issues/92#issuecomment-606318548
