### ISSUE TITLE
Link warning: attempted to exit Link when it was not open

### ISSUE THREAD

**Issue by rubendinho** [plaid/react-plaid-link#94]
In v2.0.3, after opening Link, closing, and navigating away, i get the warning in the JS console: 
`Link warning: attempted to exit Link when it was not open`

This occurs both with hook and component-based implementations.

**Comment by hkhanna** [comment]
I also get this when the plaid link instance is destroyed and recreated when the options change. I'm using the hook implementation.

**Comment by anjiren** [comment]
Hi @rubendinho and @hkhanna - this issue should be fixed after the next deploy of Link. Let me know if this doesn't go away in the next couple of days!
