### ISSUE TITLE
Export PlaidLinkOptions in Typescript

### ISSUE THREAD

**Issue by aymanbagabas** [plaid/react-plaid-link#98]
Hi,

I think it's reasonable to export the props used with PlaidLink/usePlaidLink with Typescript. This eliminates extra packages like [this](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-plaid-link).

**Comment by timruffles** [comment]
Great idea. We'd accept a PR if someone gets to it before we can (no idea when that'd be).

**Comment by wokkaflokka** [comment]
Please see #134 for a proposed fix.
